<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
  public function run(): void
  {
    $municipios = [
      ['estado_id'=> 1, 'municipio'=> 'Alto Orinoco', 'capital'=> 'La Esmeralda'], 
      ['estado_id'=> 1, 'municipio'=> 'Atabapo', 'capital'=> 'San Fernando de Atabapo'],
      ['estado_id'=> 1, 'municipio'=> 'Atures', 'capital'=> 'Puerto Ayacucho'], 
      ['estado_id'=> 1, 'municipio'=> 'Autana', 'capital'=> 'Isla Ratón'], 
      ['estado_id'=> 1, 'municipio'=> 'Manapiare', 'capital'=> 'San Juan de Manapiare'],
      ['estado_id'=> 1, 'municipio'=> 'Maroa', 'capital'=> 'Maroa'], 
      ['estado_id'=> 1, 'municipio'=> 'Río Negro', 'capital'=> 'San Carlos de Río Negro'], 
      ['estado_id'=> 2, 'municipio'=> 'Anaco', 'capital'=> 'Anaco'], 
      ['estado_id'=> 2, 'municipio'=> 'Aragua', 'capital'=> 'Aragua de Barcelona'],
      ['estado_id'=> 2, 'municipio'=> 'Bolívar', 'capital'=> 'Barcelona'], 
      ['estado_id'=> 2, 'municipio'=> 'Bruzual', 'capital'=> 'Clarines'], 
      ['estado_id'=> 2, 'municipio'=> 'Cajigal', 'capital'=> 'Onoto'], 
      ['estado_id'=> 2, 'municipio'=> 'Carvajal', 'capital'=> 'Valle de Guanape'], 
      ['estado_id'=> 2, 'municipio'=> 'Diego Bautista Urbaneja', 'capital'=> 'Lechería'], 
      ['estado_id'=> 2, 'municipio'=> 'Freites', 'capital'=> 'Cantaura'],
      ['estado_id'=> 2, 'municipio'=> 'Guanipa', 'capital'=> 'San José de Guanipa'], 
      ['estado_id'=> 2, 'municipio'=> 'Guanta', 'capital'=> 'Guanta'], 
      ['estado_id'=> 2, 'municipio'=> 'Independencia', 'capital'=> 'Soledad'], 
      ['estado_id'=> 2, 'municipio'=> 'Libertad', 'capital'=> 'San Mateo'], 
      ['estado_id'=> 2, 'municipio'=> 'McGregor', 'capital'=> 'El Chaparro'], 
      ['estado_id'=> 2, 'municipio'=> 'Miranda', 'capital'=> 'Pariaguán'], 
      ['estado_id'=> 2, 'municipio'=> 'Monagas', 'capital'=> 'Mapire'], 
      ['estado_id'=> 2, 'municipio'=> 'Peñalver', 'capital'=> 'Puerto Píritu'], 
      ['estado_id'=> 2, 'municipio'=> 'Píritu', 'capital'=> 'Píritu'], 
      ['estado_id'=> 2, 'municipio'=> 'San Juan de Capistrano', 'capital'=> 'Boca de Uchire'], 
      ['estado_id'=> 2, 'municipio'=> 'Santa Ana', 'capital'=> 'Santa Ana'], 
      ['estado_id'=> 2, 'municipio'=> 'Simón Rodríguez', 'capital'=> 'El Tigre'], 
      ['estado_id'=> 2, 'municipio'=> 'Sotillo', 'capital'=> 'Puerto La Cruz'], 
      ['estado_id'=> 3, 'municipio'=> 'Achaguas', 'capital'=> 'Achaguas'],
      ['estado_id'=> 3, 'municipio'=> 'Biruaca', 'capital'=> 'Biruaca'], 
      ['estado_id'=> 3, 'municipio'=> 'Muñoz', 'capital'=> 'Bruzual'], 
      ['estado_id'=> 3, 'municipio'=> 'Páez', 'capital'=> 'Guasdualito'], 
      ['estado_id'=> 3, 'municipio'=> 'Pedro Camejo', 'capital'=> 'San Juan de Payara'], 
      ['estado_id'=> 3, 'municipio'=> 'Rómulo Gallegos', 'capital'=> 'Elorza'], 
      ['estado_id'=> 3, 'municipio'=> 'San Fernando', 'capital'=> 'San Fernando de Apure'], 
      ['estado_id'=> 4, 'municipio'=> 'Bolívar', 'capital'=> 'San Mateo'],
      ['estado_id'=> 4, 'municipio'=> 'Camatagua', 'capital'=> 'Camatagua'], 
      ['estado_id'=> 4, 'municipio'=> 'Francisco Linares Alcántara', 'capital'=> 'Santa Rita'], 
      ['estado_id'=> 4, 'municipio'=> 'Girardot', 'capital'=> 'Maracay'], 
      ['estado_id'=> 4, 'municipio'=> 'José Ángel Lamas', 'capital'=> 'Santa Cruz de Aragua'],
      ['estado_id'=> 4, 'municipio'=> 'José Félix Ribas', 'capital'=> 'La Victoria'], 
      ['estado_id'=> 4, 'municipio'=> 'José Rafael Revenga', 'capital'=> 'El Consejo'], 
      ['estado_id'=> 4, 'municipio'=> 'Libertador', 'capital'=> 'Palo Negro'], 
      ['estado_id'=> 4, 'municipio'=> 'Mario Briceño Iragorry', 'capital'=> 'El Limón'], 
      ['estado_id'=> 4, 'municipio'=> 'Ocumare de la Costa de Oro', 'capital'=> 'Ocumare de la Costa'], 
      ['estado_id'=> 4, 'municipio'=> 'San Casimiro', 'capital'=> 'San Casimiro'], 
      ['estado_id'=> 4, 'municipio'=> 'San Sebastián', 'capital'=> 'San Sebastián de Los Reyes'],
      ['estado_id'=> 4, 'municipio'=> 'Santiago Mariño', 'capital'=> 'Turmero'], 
      ['estado_id'=> 4, 'municipio'=> 'Santos Michelena', 'capital'=> 'Las Tejerías'],
      ['estado_id'=> 4, 'municipio'=> 'Sucre', 'capital'=> 'Cagua'],
      ['estado_id'=> 4, 'municipio'=> 'Tovar', 'capital'=> 'Colonia Tovar'], 
      ['estado_id'=> 4, 'municipio'=> 'Urdaneta', 'capital'=> 'Barbacoas'], 
      ['estado_id'=> 4, 'municipio'=> 'Zamora', 'capital'=> 'Villa de Cura'],
      ['estado_id'=> 5, 'municipio'=> 'Alberto Arvelo Torrealba', 'capital'=> 'Sabaneta'], 
      ['estado_id'=> 5, 'municipio'=> 'Andrés Eloy Blanco', 'capital'=> 'El Cantón'],
      ['estado_id'=> 5, 'municipio'=> 'Antonio José de Sucre', 'capital'=> 'Socopó'], 
      ['estado_id'=> 5, 'municipio'=> 'Arismendi', 'capital'=> 'Arismendi'], 
      ['estado_id'=> 5, 'municipio'=> 'Barinas', 'capital'=> 'Barinas'], 
      ['estado_id'=> 5, 'municipio'=> 'Bolívar', 'capital'=> 'Barinitas'],
      ['estado_id'=> 5, 'municipio'=> 'Cruz Paredes', 'capital'=> 'Barrancas'], 
      ['estado_id'=> 5, 'municipio'=> 'Ezequiel Zamora', 'capital'=> 'Santa Bárbara'], 
      ['estado_id'=> 5, 'municipio'=> 'Obispos', 'capital'=> 'Obispos'], 
      ['estado_id'=> 5, 'municipio'=> 'Pedraza', 'capital'=> 'Ciudad Bolivia'], 
      ['estado_id'=> 5, 'municipio'=> 'Rojas', 'capital'=> 'Libertad'], 
      ['estado_id'=> 5, 'municipio'=> 'Sosa', 'capital'=> 'Ciudad de Nutrias'], 
      ['estado_id'=> 6, 'municipio'=> 'Angostura', 'capital'=> 'Ciudad Píar'], 
      ['estado_id'=> 6, 'municipio'=> 'Caroní', 'capital'=> 'Ciudad Guayana'],
      ['estado_id'=> 6, 'municipio'=> 'Cedeño', 'capital'=> 'Caicara del Orinoco'], 
      ['estado_id'=> 6, 'municipio'=> 'El Callao', 'capital'=> 'El Callao'], 
      ['estado_id'=> 6, 'municipio'=> 'Gran Sabana', 'capital'=> 'Santa Elena de Uairén'], 
      ['estado_id'=> 6, 'municipio'=> 'Heres', 'capital'=> 'Ciudad Bolívar'],
      ['estado_id'=> 6, 'municipio'=> 'Píar', 'capital'=> 'Upata'], 
      ['estado_id'=> 6, 'municipio'=> 'Roscio', 'capital'=> 'Guasipati'],
      ['estado_id'=> 6, 'municipio'=> 'Sifontes', 'capital'=> 'El Dorado'], 
      ['estado_id'=> 6, 'municipio'=> 'Sucre', 'capital'=> 'Maripa'], 
      ['estado_id'=> 6, 'municipio'=> 'Padre Pedro Chien', 'capital'=> 'El Palmar'], 
      ['estado_id'=> 7, 'municipio'=> 'Bejuma', 'capital'=> 'Bejuma'],
      ['estado_id'=> 7, 'municipio'=> 'Carlos Arvelo', 'capital'=> 'Güigüe'], 
      ['estado_id'=> 7, 'municipio'=> 'Diego Ibarra', 'capital'=> 'Mariara'], 
      ['estado_id'=> 7, 'municipio'=> 'Guacara', 'capital'=> 'Guacara'],
      ['estado_id'=> 7, 'municipio'=> 'Mora', 'capital'=> 'Morón'], 
      ['estado_id'=> 7, 'municipio'=> 'Libertador', 'capital'=> 'Tocuyito'],
      ['estado_id'=> 7, 'municipio'=> 'Los Guayos', 'capital'=> 'Los Guayos'], 
      ['estado_id'=> 7, 'municipio'=> 'Miranda', 'capital'=> 'Miranda'], 
      ['estado_id'=> 7, 'municipio'=> 'Montalbán', 'capital'=> 'Montalbán'], 
      ['estado_id'=> 7, 'municipio'=> 'Naguanagua', 'capital'=> 'Naguanagua'],
      ['estado_id'=> 7, 'municipio'=> 'Puerto Cabello', 'capital'=> 'Puerto Cabello'],
      ['estado_id'=> 7, 'municipio'=> 'San Diego', 'capital'=> 'San Diego'], 
      ['estado_id'=> 7, 'municipio'=> 'San Joaquín', 'capital'=> 'San Joaquín'],
      ['estado_id'=> 7, 'municipio'=> 'Valencia', 'capital'=> 'Valencia'], 
      ['estado_id'=> 8, 'municipio'=> 'Anzoátegui', 'capital'=> 'Cojedes'],
      ['estado_id'=> 8, 'municipio'=> 'Tinaquillo', 'capital'=> 'Tinaquillo'],
      ['estado_id'=> 8, 'municipio'=> 'Girardot', 'capital'=> 'El Baúl'], 
      ['estado_id'=> 8, 'municipio'=> 'Lima Blanco', 'capital'=> 'Macapo'],
      ['estado_id'=> 8, 'municipio'=> 'Pao de San Juan Bautista', 'capital'=> 'El Pao'], 
      ['estado_id'=> 8, 'municipio'=> 'Ricaurte', 'capital'=> 'Libertad'],
      ['estado_id'=> 8, 'municipio'=> 'Rómulo Gallegos', 'capital'=> 'Las Vegas'],
      ['estado_id'=> 8, 'municipio'=> 'San Carlos', 'capital'=> 'San Carlos'],
      ['estado_id'=> 8, 'municipio'=> 'Tinaco', 'capital'=> 'Tinaco'], 
      ['estado_id'=> 9, 'municipio'=> 'Antonio Díaz', 'capital'=> 'Curiapo'], 
      ['estado_id'=> 9, 'municipio'=> 'Casacoima', 'capital'=> 'Sierra Imataca'], 
      ['estado_id'=> 9, 'municipio'=> 'Pedernales', 'capital'=> 'Pedernales'],
      ['estado_id'=> 9, 'municipio'=> 'Tucupita', 'capital'=> 'Tucupita'],
      ['estado_id'=> 10, 'municipio'=> 'Acosta', 'capital'=> 'San Juan de los Cayos'], 
      ['estado_id'=> 10, 'municipio'=> 'Bolívar', 'capital'=> 'San Luis'], 
      ['estado_id'=> 10, 'municipio'=> 'Buchivacoa', 'capital'=> 'Capatárida'], 
      ['estado_id'=> 10, 'municipio'=> 'Carirubana', 'capital'=> 'Punto Fijo'],
      ['estado_id'=> 10, 'municipio'=> 'Colina', 'capital'=> 'La Vela de Coro'],
      ['estado_id'=> 10, 'municipio'=> 'Dabajuro', 'capital'=> 'Dabajuro'], 
      ['estado_id'=> 10, 'municipio'=> 'Democracia', 'capital'=> 'Pedregal'], 
      ['estado_id'=> 10, 'municipio'=> 'Falcón', 'capital'=> 'Pueblo Nuevo'],
      ['estado_id'=> 10, 'municipio'=> 'Federación', 'capital'=> 'Churuguara'], 
      ['estado_id'=> 10, 'municipio'=> 'Jacura', 'capital'=> 'Jacura'], 
      ['estado_id'=> 10, 'municipio'=> 'Los Taques', 'capital'=> 'Santa Cruz de Los Taques'],
      ['estado_id'=> 10, 'municipio'=> 'Manaure', 'capital'=> 'Yaracal'],
      ['estado_id'=> 10, 'municipio'=> 'Mauroa', 'capital'=> 'Mene de Mauroa'],
      ['estado_id'=> 10, 'municipio'=> 'Miranda', 'capital'=> 'Santa Ana de Coro'], 
      ['estado_id'=> 10, 'municipio'=> 'Monseñor Iturriza', 'capital'=> 'Chichiriviche'], 
      ['estado_id'=> 10, 'municipio'=> 'Palmasola', 'capital'=> 'Palmasola'], 
      ['estado_id'=> 10, 'municipio'=> 'Petit', 'capital'=> 'Cabure'],
      ['estado_id'=> 10, 'municipio'=> 'Píritu', 'capital'=> 'Píritu'], 
      ['estado_id'=> 10, 'municipio'=> 'San Francisco', 'capital'=> 'Mirimire'], 
      ['estado_id'=> 10, 'municipio'=> 'Sucre', 'capital'=> 'La Cruz de Taratara'], 
      ['estado_id'=> 10, 'municipio'=> 'Silva', 'capital'=> 'Tucacas'], 
      ['estado_id'=> 10, 'municipio'=> 'Tocópero', 'capital'=> 'Tocópero'],
      ['estado_id'=> 10, 'municipio'=> 'Unión', 'capital'=> 'Santa Cruz de Bucaral'], 
      ['estado_id'=> 10, 'municipio'=> 'Urumaco', 'capital'=> 'Urumaco'], 
      ['estado_id'=> 10, 'municipio'=> 'Zamora', 'capital'=> 'Puerto Cumarebo'], 
      ['estado_id'=> 11, 'municipio'=> 'Chaguaramas', 'capital'=> 'Chaguaramas'], 
      ['estado_id'=> 11, 'municipio'=> 'El Socorro', 'capital'=> 'El Socorro'], 
      ['estado_id'=> 11, 'municipio'=> 'Infante', 'capital'=> 'Valle de La Pascua'], 
      ['estado_id'=> 11, 'municipio'=> 'Las Mercedes', 'capital'=> 'Las Mercedes'], 
      ['estado_id'=> 11, 'municipio'=> 'Camaguán', 'capital'=> 'Camaguán'], 
      ['estado_id'=> 11, 'municipio'=> 'Mellado', 'capital'=> 'El Sombrero'], 
      ['estado_id'=> 11, 'municipio'=> 'Miranda', 'capital'=> 'Calabozo'], 
      ['estado_id'=> 11, 'municipio'=> 'Monagas', 'capital'=> 'Altagracia de Orituco'], 
      ['estado_id'=> 11, 'municipio'=> 'Ortiz', 'capital'=> 'Ortiz'], 
      ['estado_id'=> 11, 'municipio'=> 'Ribas', 'capital'=> 'Tucupido'], 
      ['estado_id'=> 11, 'municipio'=> 'Roscio', 'capital'=> 'San Juan de Los Morros'],
      ['estado_id'=> 11, 'municipio'=> 'San Gerónimo de Guayabal', 'capital'=> 'Guayabal'],
      ['estado_id'=> 11, 'municipio'=> 'San José de Guaribe', 'capital'=> 'San José de Guaribe'],
      ['estado_id'=> 11, 'municipio'=> 'Santa María de Ipire', 'capital'=> 'Santa María de Ipire'],
      ['estado_id'=> 11, 'municipio'=> 'Zaraza', 'capital'=> 'Zaraza'],
      ['estado_id'=> 12, 'municipio'=> 'Andrés Eloy Blanco', 'capital'=> 'Sanare'], 
      ['estado_id'=> 12, 'municipio'=> 'Crespo', 'capital'=> 'Duaca'], 
      ['estado_id'=> 12, 'municipio'=> 'Iribarren', 'capital'=> 'Barquisimeto'], 
      ['estado_id'=> 12, 'municipio'=> 'Jiménez', 'capital'=> 'Quibor'], 
      ['estado_id'=> 12, 'municipio'=> 'Morán', 'capital'=> 'El Tocuyo'],
      ['estado_id'=> 12, 'municipio'=> 'Palavecino', 'capital'=> 'Cabudare'],
      ['estado_id'=> 12, 'municipio'=> 'Simón Planas', 'capital'=> 'Sarare'], 
      ['estado_id'=> 12, 'municipio'=> 'Torres', 'capital'=> 'Carora'], 
      ['estado_id'=> 12, 'municipio'=> 'Urdaneta', 'capital'=> 'Siquisique'], 
      ['estado_id'=> 13, 'municipio'=> 'Alberto Adriani', 'capital'=> 'El Vigía'],
      ['estado_id'=> 13, 'municipio'=> 'Andrés Bello', 'capital'=> 'La Azulita'],
      ['estado_id'=> 13, 'municipio'=> 'Antonio Pinto Salinas', 'capital'=> 'Santa Cruz de Mora'], 
      ['estado_id'=> 13, 'municipio'=> 'Aricagua', 'capital'=> 'Aricagua'],
      ['estado_id'=> 13, 'municipio'=> 'Arzobispo Chacón', 'capital'=> 'Canaguá'],
      ['estado_id'=> 13, 'municipio'=> 'Campo Elías', 'capital'=> 'Ejido'], 
      ['estado_id'=> 13, 'municipio'=> 'Caracciolo Parra Olmedo', 'capital'=> 'Tucaní'],
      ['estado_id'=> 13, 'municipio'=> 'Cardenal Quintero', 'capital'=> 'Santo Domingo'],
      ['estado_id'=> 13, 'municipio'=> 'Guaraque', 'capital'=> 'Guaraque'], 
      ['estado_id'=> 13, 'municipio'=> 'Julio César Salas', 'capital'=> 'Arapuey'],
      ['estado_id'=> 13, 'municipio'=> 'Justo Briceño', 'capital'=> 'Torondoy'],
      ['estado_id'=> 13, 'municipio'=> 'Libertador', 'capital'=> 'Mérida'],
      ['estado_id'=> 13, 'municipio'=> 'Miranda', 'capital'=> 'Timotes'], 
      ['estado_id'=> 13, 'municipio'=> 'Obispo Ramos de Lora', 'capital'=> 'Santa Elena de Arenales'], 
      ['estado_id'=> 13, 'municipio'=> 'Padre Noguera', 'capital'=> 'Santa María de Caparo'],
      ['estado_id'=> 13, 'municipio'=> 'Pueblo Llano', 'capital'=> 'Pueblo Llano'],
      ['estado_id'=> 13, 'municipio'=> 'Rangel', 'capital'=> 'Mucuchíes'],
      ['estado_id'=> 13, 'municipio'=> 'Rivas Dávila', 'capital'=> 'Bailadores'],
      ['estado_id'=> 13, 'municipio'=> 'Santos Marquina', 'capital'=> 'Tabay'],
      ['estado_id'=> 13, 'municipio'=> 'Sucre', 'capital'=> 'Lagunillas'],
      ['estado_id'=> 13, 'municipio'=> 'Tovar', 'capital'=> 'Tovar'],
      ['estado_id'=> 13, 'municipio'=> 'Tulio Febres Cordero', 'capital'=> 'Nueva Bolivia'], 
      ['estado_id'=> 13, 'municipio'=> 'Zea', 'capital'=> 'Zea'],
      ['estado_id'=> 14, 'municipio'=> 'Acevedo', 'capital'=> 'Caucagua'], 
      ['estado_id'=> 14, 'municipio'=> 'Andrés Bello', 'capital'=> 'San José de Barlovento'], 
      ['estado_id'=> 14, 'municipio'=> 'Baruta', 'capital'=> 'Baruta'],
      ['estado_id'=> 14, 'municipio'=> 'Brión', 'capital'=> 'Higuerote'],
      ['estado_id'=> 14, 'municipio'=> 'Buroz', 'capital'=> 'Mamporal'], 
      ['estado_id'=> 14, 'municipio'=> 'Carrizal', 'capital'=> 'Carrizal'], 
      ['estado_id'=> 14, 'municipio'=> 'Chacao', 'capital'=> 'Chacao'], 
      ['estado_id'=> 14, 'municipio'=> 'Cristóbal Rojas', 'capital'=> 'Charallave'], 
      ['estado_id'=> 14, 'municipio'=> 'El Hatillo', 'capital'=> 'Santa Rosalía de Palermo'],
      ['estado_id'=> 14, 'municipio'=> 'Guaicaipuro', 'capital'=> 'Los Teques'], 
      ['estado_id'=> 14, 'municipio'=> 'Independencia', 'capital'=> 'Santa Teresa del Tuy'], 
      ['estado_id'=> 14, 'municipio'=> 'Lander', 'capital'=> 'Ocumare del Tuy'], 
      ['estado_id'=> 14, 'municipio'=> 'Los Salias', 'capital'=> 'San Antonio de los Altos'],
      ['estado_id'=> 14, 'municipio'=> 'Páez', 'capital'=> 'Río Chico'],
      ['estado_id'=> 14, 'municipio'=> 'Paz Castillo', 'capital'=> 'Santa Lucía'],
      ['estado_id'=> 14, 'municipio'=> 'Pedro Gual', 'capital'=> 'Cúpira'], 
      ['estado_id'=> 14, 'municipio'=> 'Plaza', 'capital'=> 'Guarenas'], 
      ['estado_id'=> 14, 'municipio'=> 'Simón Bolívar', 'capital'=> 'San Francisco de Yare'],
      ['estado_id'=> 14, 'municipio'=> 'Sucre', 'capital'=> 'Petare'],
      ['estado_id'=> 14, 'municipio'=> 'Urdaneta', 'capital'=> 'Cúa'], 
      ['estado_id'=> 14, 'municipio'=> 'Zamora', 'capital'=> 'Guatire'], 
      ['estado_id'=> 15, 'municipio'=> 'Acosta', 'capital'=> 'San Antonio de Capayacuar'], 
      ['estado_id'=> 15, 'municipio'=> 'Aguasay', 'capital'=> 'Aguasay'],
      ['estado_id'=> 15, 'municipio'=> 'Bolívar', 'capital'=> 'Caripito'],
      ['estado_id'=> 15, 'municipio'=> 'Caripe', 'capital'=> 'Caripe'], 
      ['estado_id'=> 15, 'municipio'=> 'Cedeño', 'capital'=> 'Caicara de Maturín'], 
      ['estado_id'=> 15, 'municipio'=> 'Ezequiel Zamora', 'capital'=> 'Punta de Mata'], 
      ['estado_id'=> 15, 'municipio'=> 'Libertador', 'capital'=> 'Temblador'], 
      ['estado_id'=> 15, 'municipio'=> 'Maturín', 'capital'=> 'Maturín'],
      ['estado_id'=> 15, 'municipio'=> 'Piar', 'capital'=> 'Aragua de Maturín'],
      ['estado_id'=> 15, 'municipio'=> 'Punceres', 'capital'=> 'Quiriquire'],
      ['estado_id'=> 15, 'municipio'=> 'Santa Bárbara', 'capital'=> 'Santa Bárbara'],
      ['estado_id'=> 15, 'municipio'=> 'Sotillo', 'capital'=> 'Barrancas del Orinoco'],
      ['estado_id'=> 15, 'municipio'=> 'Uracoa', 'capital'=> 'Uracoa'], 
      ['estado_id'=> 16, 'municipio'=> 'Antolín del Campo', 'capital'=> 'Paraguachí'], 
      ['estado_id'=> 16, 'municipio'=> 'Arismendi', 'capital'=> 'La Asunción'],
      ['estado_id'=> 16, 'municipio'=> 'Díaz', 'capital'=> 'San Juan Bautista'],
      ['estado_id'=> 16, 'municipio'=> 'García', 'capital'=> 'El Valle'], 
      ['estado_id'=> 16, 'municipio'=> 'Gómez', 'capital'=> 'Santa Ana'],
      ['estado_id'=> 16, 'municipio'=> 'Maneiro', 'capital'=> 'Pampatar'],
      ['estado_id'=> 16, 'municipio'=> 'Marcano', 'capital'=> 'Juan Griego'],
      ['estado_id'=> 16, 'municipio'=> 'Mariño', 'capital'=> 'Porlamar'], 
      ['estado_id'=> 16, 'municipio'=> 'Península de Macanao', 'capital'=> 'Boca de Río'],
      ['estado_id'=> 16, 'municipio'=> 'Tubores', 'capital'=> 'Punta de Piedras'], 
      ['estado_id'=> 16, 'municipio'=> 'Villalba', 'capital'=> 'San Pedro de Coche'],
      ['estado_id'=> 17, 'municipio'=> 'Agua Blanca', 'capital'=> 'Agua Blanca'], 
      ['estado_id'=> 17, 'municipio'=> 'Araure', 'capital'=> 'Araure'],
      ['estado_id'=> 17, 'municipio'=> 'Esteller', 'capital'=> 'Píritu'], 
      ['estado_id'=> 17, 'municipio'=> 'Guanare', 'capital'=> 'Guanare'], 
      ['estado_id'=> 17, 'municipio'=> 'Guanarito', 'capital'=> 'Guanarito'],
      ['estado_id'=> 17, 'municipio'=> 'Monseñor José Vicente de Unda', 'capital'=> 'Paraíso de Chabasquén'],
      ['estado_id'=> 17, 'municipio'=> 'Ospino', 'capital'=> 'Ospino'], 
      ['estado_id'=> 17, 'municipio'=> 'Páez', 'capital'=> 'Acarigua'], 
      ['estado_id'=> 17, 'municipio'=> 'Papelón', 'capital'=> 'Papelón'], 
      ['estado_id'=> 17, 'municipio'=> 'San Genaro de Boconoíto', 'capital'=> 'Boconoíto'],
      ['estado_id'=> 17, 'municipio'=> 'San Rafael de Onoto', 'capital'=> 'San Rafael de Onoto'], 
      ['estado_id'=> 17, 'municipio'=> 'Santa Rosalía', 'capital'=> 'El Playón'], 
      ['estado_id'=> 17, 'municipio'=> 'Sucre', 'capital'=> 'Biscucuy'], 
      ['estado_id'=> 17, 'municipio'=> 'Turén', 'capital'=> 'Villa Bruzual'],
      ['estado_id'=> 18, 'municipio'=> 'Andrés Eloy Blanco', 'capital'=> 'Casanay'],
      ['estado_id'=> 18, 'municipio'=> 'Andrés Mata', 'capital'=> 'San José de Aerocuar'], 
      ['estado_id'=> 18, 'municipio'=> 'Arismendi', 'capital'=> 'Río Caribe'],
      ['estado_id'=> 18, 'municipio'=> 'Benítez', 'capital'=> 'El Pilar'], 
      ['estado_id'=> 18, 'municipio'=> 'Bermúdez', 'capital'=> 'Carúpano'],
      ['estado_id'=> 18, 'municipio'=> 'Bolívar', 'capital'=> 'Marigüitar'],
      ['estado_id'=> 18, 'municipio'=> 'Cajigal', 'capital'=> 'Yaguaraparo'], 
      ['estado_id'=> 18, 'municipio'=> 'Cruz Salmerón Acosta', 'capital'=> 'Araya'], 
      ['estado_id'=> 18, 'municipio'=> 'Libertador', 'capital'=> 'Tunapuy'], 
      ['estado_id'=> 18, 'municipio'=> 'Mariño', 'capital'=> 'Irapa'], 
      ['estado_id'=> 18, 'municipio'=> 'Mejía', 'capital'=> 'San Antonio del Golfo'], 
      ['estado_id'=> 18, 'municipio'=> 'Montes', 'capital'=> 'Cumanacoa'], 
      ['estado_id'=> 18, 'municipio'=> 'Ribero', 'capital'=> 'Cariaco'], 
      ['estado_id'=> 18, 'municipio'=> 'Sucre', 'capital'=> 'Cumaná'], 
      ['estado_id'=> 18, 'municipio'=> 'Valdez', 'capital'=> 'Güiria'], 
      ['estado_id'=> 19, 'municipio'=> 'Andrés Bello', 'capital'=> 'Cordero'],
      ['estado_id'=> 19, 'municipio'=> 'Antonio Rómulo Costa', 'capital'=> 'Las Mesas'], 
      ['estado_id'=> 19, 'municipio'=> 'Ayacucho', 'capital'=> 'Colón'],
      ['estado_id'=> 19, 'municipio'=> 'Bolívar', 'capital'=> 'San Antonio del Táchira'],
      ['estado_id'=> 19, 'municipio'=> 'Cárdenas', 'capital'=> 'Táriba'],
      ['estado_id'=> 19, 'municipio'=> 'Córdoba', 'capital'=> 'Santa Ana de Táchira'], 
      ['estado_id'=> 19, 'municipio'=> 'Fernández Feo', 'capital'=> 'San Rafael del Piñal'], 
      ['estado_id'=> 19, 'municipio'=> 'Francisco de Miranda', 'capital'=> 'San José de Bolívar'],
      ['estado_id'=> 19, 'municipio'=> 'García de Hevia', 'capital'=> 'La Fría'],
      ['estado_id'=> 19, 'municipio'=> 'Guásimos', 'capital'=> 'Palmira'], 
      ['estado_id'=> 19, 'municipio'=> 'Independencia', 'capital'=> 'Capacho Nuevo'], 
      ['estado_id'=> 19, 'municipio'=> 'Jáuregui', 'capital'=> 'La Grita'], 
      ['estado_id'=> 19, 'municipio'=> 'José María Vargas', 'capital'=> 'El Cobre'],
      ['estado_id'=> 19, 'municipio'=> 'Junín', 'capital'=> 'Rubio'], 
      ['estado_id'=> 19, 'municipio'=> 'Libertad', 'capital'=> 'Capacho Viejo'],
      ['estado_id'=> 19, 'municipio'=> 'Libertador', 'capital'=> 'Abejales'], 
      ['estado_id'=> 19, 'municipio'=> 'Lobatera', 'capital'=> 'Lobatera'],
      ['estado_id'=> 19, 'municipio'=> 'Michelena', 'capital'=> 'Michelena'],
      ['estado_id'=> 19, 'municipio'=> 'Panamericano', 'capital'=> 'Coloncito'],
      ['estado_id'=> 19, 'municipio'=> 'Pedro María Ureña', 'capital'=> 'Ureña'],
      ['estado_id'=> 19, 'municipio'=> 'Rafael Urdaneta', 'capital'=> 'Delicias'],
      ['estado_id'=> 19, 'municipio'=> 'Samuel Darío Maldonado', 'capital'=> 'La Tendida'],
      ['estado_id'=> 19, 'municipio'=> 'San Cristóbal', 'capital'=> 'San Cristóbal'],
      ['estado_id'=> 19, 'municipio'=> 'Seboruco', 'capital'=> 'Seboruco'],
      ['estado_id'=> 19, 'municipio'=> 'Simón Rodríguez', 'capital'=> 'San Simón'],
      ['estado_id'=> 19, 'municipio'=> 'Sucre', 'capital'=> 'Queniquea'], 
      ['estado_id'=> 19, 'municipio'=> 'Torbes', 'capital'=> 'San Josecito'],
      ['estado_id'=> 19, 'municipio'=> 'Uribante', 'capital'=> 'Pregonero'], 
      ['estado_id'=> 19, 'municipio'=> 'San Judas Tadeo', 'capital'=> 'Umuquena'], 
      ['estado_id'=> 20, 'municipio'=> 'Andrés Bello', 'capital'=> 'Santa Isabel'], 
      ['estado_id'=> 20, 'municipio'=> 'Boconó', 'capital'=> 'Boconó'], 
      ['estado_id'=> 20, 'municipio'=> 'Bolívar', 'capital'=> 'Sabana Grande'], 
      ['estado_id'=> 20, 'municipio'=> 'Candelaria', 'capital'=> 'Chejendé'],
      ['estado_id'=> 20, 'municipio'=> 'Carache', 'capital'=> 'Carache'],
      ['estado_id'=> 20, 'municipio'=> 'Escuque', 'capital'=> 'Escuque'], 
      ['estado_id'=> 20, 'municipio'=> 'José Felipe Márquez Cañizalez', 'capital'=> 'El Paradero'], 
      ['estado_id'=> 20, 'municipio'=> 'Juan Vicente Campos Elías', 'capital'=> 'Campo Elías'], 
      ['estado_id'=> 20, 'municipio'=> 'La Ceiba', 'capital'=> 'Santa Apolonia'], 
      ['estado_id'=> 20, 'municipio'=> 'Miranda', 'capital'=> 'El Dividive'], 
      ['estado_id'=> 20, 'municipio'=> 'Monte Carmelo', 'capital'=> 'Monte Carmelo'], 
      ['estado_id'=> 20, 'municipio'=> 'Motatán', 'capital'=> 'Motatán'], 
      ['estado_id'=> 20, 'municipio'=> 'Pampán', 'capital'=> 'Pampán'], 
      ['estado_id'=> 20, 'municipio'=> 'Pampanito', 'capital'=> 'Pampanito'],
      ['estado_id'=> 20, 'municipio'=> 'Rafael Rangel', 'capital'=> 'Betijoque'], 
      ['estado_id'=> 20, 'municipio'=> 'San Rafael de Carvajal', 'capital'=> 'Carvajal'],
      ['estado_id'=> 20, 'municipio'=> 'Sucre', 'capital'=> 'Sabana de Mendoza'],
      ['estado_id'=> 20, 'municipio'=> 'Trujillo', 'capital'=> 'Trujillo'],
      ['estado_id'=> 20, 'municipio'=> 'Urdaneta', 'capital'=> 'La Quebrada'], 
      ['estado_id'=> 20, 'municipio'=> 'Valera', 'capital'=> 'Valera'],
      ['estado_id'=> 21, 'municipio'=> 'Vargas', 'capital'=> 'Vargas'], 
      ['estado_id'=> 22, 'municipio'=> 'Arístides Bastidas', 'capital'=> 'San Pablo'], 
      ['estado_id'=> 22, 'municipio'=> 'Bolívar', 'capital'=> 'Aroa'],
      ['estado_id'=> 22, 'municipio'=> 'Bruzual', 'capital'=> 'Chivacoa'],
      ['estado_id'=> 22, 'municipio'=> 'Cocorote', 'capital'=> 'Cocorote'], 
      ['estado_id'=> 22, 'municipio'=> 'Independencia', 'capital'=> 'Independencia'], 
      ['estado_id'=> 22, 'municipio'=> 'José Antonio Páez', 'capital'=> 'Sabana de Parra'], 
      ['estado_id'=> 22, 'municipio'=> 'La Trinidad', 'capital'=> 'Boraure'], 
      ['estado_id'=> 22, 'municipio'=> 'Manuel Monge', 'capital'=> 'Yumare'], 
      ['estado_id'=> 22, 'municipio'=> 'Nirgua', 'capital'=> 'Nirgua'], 
      ['estado_id'=> 22, 'municipio'=> 'Peña', 'capital'=> 'Yaritagua'], 
      ['estado_id'=> 22, 'municipio'=> 'San Felipe', 'capital'=> 'San Felipe'], 
      ['estado_id'=> 22, 'municipio'=> 'Sucre', 'capital'=> 'Guama'], 
      ['estado_id'=> 22, 'municipio'=> 'Urachiche', 'capital'=> 'Urachiche'],
      ['estado_id'=> 22, 'municipio'=> 'Veroes', 'capital'=> 'Farriar'], 
      ['estado_id'=> 23, 'municipio'=> 'Almirante Padilla', 'capital'=> 'El Toro'], 
      ['estado_id'=> 23, 'municipio'=> 'Baralt', 'capital'=> 'San Timoteo'],
      ['estado_id'=> 23, 'municipio'=> 'Cabimas', 'capital'=> 'Cabimas'], 
      ['estado_id'=> 23, 'municipio'=> 'Catatumbo', 'capital'=> 'Encontrados'], 
      ['estado_id'=> 23, 'municipio'=> 'Colón', 'capital'=> 'San Carlos del Zulia'], 
      ['estado_id'=> 23, 'municipio'=> 'Francisco Javier Pulgar', 'capital'=> 'Pueblo Nuevo - El Chivo'], 
      ['estado_id'=> 23, 'municipio'=> 'Páez', 'capital'=> 'Sinamaica'], 
      ['estado_id'=> 23, 'municipio'=> 'Jesús Enrique Lossada', 'capital'=> 'La Concepción'], 
      ['estado_id'=> 23, 'municipio'=> 'Jesús María Semprún', 'capital'=> 'Casigua - El Cubo'],
      ['estado_id'=> 23, 'municipio'=> 'La Cañada de Urdaneta', 'capital'=> 'La Concepción'],
      ['estado_id'=> 23, 'municipio'=> 'Lagunillas', 'capital'=> 'Ciudad Ojeda'], 
      ['estado_id'=> 23, 'municipio'=> 'Machiques de Perijá', 'capital'=> 'Machiques'], 
      ['estado_id'=> 23, 'municipio'=> 'Mara', 'capital'=> 'San Rafael de El Moján'], 
      ['estado_id'=> 23, 'municipio'=> 'Maracaibo', 'capital'=> 'Maracaibo'], 
      ['estado_id'=> 23, 'municipio'=> 'Miranda', 'capital'=> 'Los Puertos de Altagracia'], 
      ['estado_id'=> 23, 'municipio'=> 'Rosario de Perijá', 'capital'=> 'La Villa del Rosario'], 
      ['estado_id'=> 23, 'municipio'=> 'San Francisco', 'capital'=> 'San Francisco'],
      ['estado_id'=> 23, 'municipio'=> 'Santa Rita', 'capital'=> 'Santa Rita'], 
      ['estado_id'=> 23, 'municipio'=> 'Simón Bolívar', 'capital'=> 'Tía Juana'], 
      ['estado_id'=> 23, 'municipio'=> 'Sucre', 'capital'=> 'Bobures'], 
      ['estado_id'=> 23, 'municipio'=> 'Valmore Rodríguez', 'capital'=> 'Bachaquero'],
      ['estado_id'=> 24, 'municipio'=> 'Libertador', 'capital'=> 'Caracas'],
    ]; 

    DB::table('municipios')->insert($municipios);  
  }
}
  