<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParroquiasSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $parroquias = [
      ['parroquia' => 'Alto Orinoco La Esmeralda', 'municipio_id' => 1],
      ['parroquia' => 'Huachamacare Acanaña', 'municipio_id' => 1],
      ['parroquia' => 'Marawaka Toky Shamanaña', 'municipio_id' => 1],
      ['parroquia' => 'Mavaka Mavaka', 'municipio_id' => 1],
      ['parroquia' => 'Sierra Parima Parimabé', 'municipio_id' => 1],
      ['parroquia' => 'Ucata Laja Lisa', 'municipio_id' => 2],
      ['parroquia' => 'Yapacana Macuruco', 'municipio_id' => 2],
      ['parroquia' => 'Caname Guarinuma', 'municipio_id' => 2],
      ['parroquia' => 'Fernando Girón Tovar', 'municipio_id' => 3],
      ['parroquia' => 'Luis Alberto Gómez', 'municipio_id' => 3],
      ['parroquia' => 'Pahueña Limón de Parhueña', 'municipio_id' => 3],
      ['parroquia' => 'Platanillal Platanillal', 'municipio_id' => 3],
      ['parroquia' => 'Samariapo Samariapo', 'municipio_id' => 4],
      ['parroquia' => 'Sipapo Pendare', 'municipio_id' => 4],
      ['parroquia' => 'Munduapo Munduapo', 'municipio_id' => 4],
      ['parroquia' => 'Guayapo San Pedro del Orinoco', 'municipio_id' => 4],
      ['parroquia' => 'Alto Ventuari Cacurí', 'municipio_id' => 5],
      ['parroquia' => 'Medio Ventuari Manami', 'municipio_id' => 5],
      ['parroquia' => 'Bajo Ventuari Marueta', 'municipio_id' => 5],
      ['parroquia' => 'Victorino', 'municipio_id' => 6],
      ['parroquia' => 'Comunidad', 'municipio_id' => 6],
      ['parroquia' => 'Casiquiare Curimacare', 'municipio_id' => 7],
      ['parroquia' => 'Cocuy', 'municipio_id' => 7],
      ['parroquia' => 'San Carlos de Río Negro', 'municipio_id' => 7],
      ['parroquia' => 'Solano Solano', 'municipio_id' => 7],
      ['parroquia' => 'Anaco', 'municipio_id' => 8],
      ['parroquia' => 'San Joaquín', 'municipio_id' => 8],
      ['parroquia' => 'Cachipo', 'municipio_id' => 9],
      ['parroquia' => 'Aragua de Barcelona', 'municipio_id' => 9],
      ['parroquia' => 'Bergatín', 'municipio_id' => 10],
      ['parroquia' => 'Caigua', 'municipio_id' => 10],
      ['parroquia' => 'El Carmen.', 'municipio_id' => 10],
      ['parroquia' => 'El Pilar', 'municipio_id' => 10],
      ['parroquia' => 'Naricual.', 'municipio_id' => 10],
      ['parroquia' => 'San Cristóbal', 'municipio_id' => 10],
      ['parroquia' => 'Clarines', 'municipio_id' => 11],
      ['parroquia' => 'Guanape', 'municipio_id' => 11],
      ['parroquia' => 'Sabana de Uchire', 'municipio_id' => 11],
      ['parroquia' => 'Onoto', 'municipio_id' => 12],
      ['parroquia' => 'San Pablo', 'municipio_id' => 12],
      ['parroquia' => 'Valle de Guanape', 'municipio_id' => 13],
      ['parroquia' => 'Santa Bárbara', 'municipio_id' => 13],
      ['parroquia' => 'Lechería', 'municipio_id' => 14],
      ['parroquia' => 'El Morro', 'municipio_id' => 14],
      ['parroquia' => 'Cantaura', 'municipio_id' => 15],
      ['parroquia' => 'Libertador', 'municipio_id' => 15],
      ['parroquia' => 'Santa Rosa', 'municipio_id' => 15],
      ['parroquia' => 'Urica', 'municipio_id' => 15],
      ['parroquia' => 'San José de Guanipa', 'municipio_id' => 16],
      ['parroquia' => 'Guanta', 'municipio_id' => 17],
      ['parroquia' => 'Chorrerón', 'municipio_id' => 17],
      ['parroquia' => 'Mamo', 'municipio_id' => 18],
      ['parroquia' => 'Soledad', 'municipio_id' => 18],
      ['parroquia' => 'San Mateo', 'municipio_id' => 19],
      ['parroquia' => 'El Carito', 'municipio_id' => 19],
      ['parroquia' => 'Santa Inés', 'municipio_id' => 19],
      ['parroquia' => 'La Romereña', 'municipio_id' => 19],
      ['parroquia' => 'El Chaparro', 'municipio_id' => 20],
      ['parroquia' => 'Tomás Alfaro', 'municipio_id' => 20],
      ['parroquia' => 'Calatrava', 'municipio_id' => 20],
      ['parroquia' => 'Atapirire', 'municipio_id' => 21],
      ['parroquia' => 'Boca del Pao', 'municipio_id' => 21],
      ['parroquia' => 'El Pao', 'municipio_id' => 21],
      ['parroquia' => 'Pariaguán', 'municipio_id' => 21],
      ['parroquia' => 'Mapire', 'municipio_id' => 22],
      ['parroquia' => 'Piar', 'municipio_id' => 22],
      ['parroquia' => 'Santa Clara', 'municipio_id' => 22],
      ['parroquia' => 'San Diego de Cabrutica', 'municipio_id' => 22],
      ['parroquia' => 'Uverito', 'municipio_id' => 22],
      ['parroquia' => 'Zuata', 'municipio_id' => 22],
      ['parroquia' => 'Puerto Píritu', 'municipio_id' => 23],
      ['parroquia' => 'San Miguel', 'municipio_id' => 23],
      ['parroquia' => 'Sucre', 'municipio_id' => 23],
      ['parroquia' => 'Píritu', 'municipio_id' => 24],
      ['parroquia' => 'San Francisco', 'municipio_id' => 24],
      ['parroquia' => 'Boca de Uchire', 'municipio_id' => 25],
      ['parroquia' => 'Boca de Chávez', 'municipio_id' => 25],
      ['parroquia' => 'Pueblo Nuevo', 'municipio_id' => 26],
      ['parroquia' => 'Santa Ana', 'municipio_id' => 26],
      ['parroquia' => 'Edmundo Barrios', 'municipio_id' => 27],
      ['parroquia' => 'Miguel Otero Silva', 'municipio_id' => 27],
      ['parroquia' => 'Puerto La Cruz', 'municipio_id' => 28],
      ['parroquia' => 'Pozuelos', 'municipio_id' => 28],
      ['parroquia' => 'Achaguas', 'municipio_id' => 29],
      ['parroquia' => 'Apurito', 'municipio_id' => 29],
      ['parroquia' => 'El Yagual', 'municipio_id' => 29],
      ['parroquia' => 'Guachara', 'municipio_id' => 29],
      ['parroquia' => 'Mucuritas', 'municipio_id' => 29],
      ['parroquia' => 'Queseras del medio', 'municipio_id' => 29],
      ['parroquia' => 'Biruaca', 'municipio_id' => 30],
      ['parroquia' => 'Bruzual', 'municipio_id' => 31],
      ['parroquia' => 'Mantecal', 'municipio_id' => 31],
      ['parroquia' => 'Quintero', 'municipio_id' => 31],
      ['parroquia' => 'Rincón Hondo', 'municipio_id' => 31],
      ['parroquia' => 'San Vicente', 'municipio_id' => 31],
      ['parroquia' => 'Guasdualito', 'municipio_id' => 32],
      ['parroquia' => 'Aramendi', 'municipio_id' => 32],
      ['parroquia' => 'El Amparo', 'municipio_id' => 32],
      ['parroquia' => 'San Camilo', 'municipio_id' => 32],
      ['parroquia' => 'Urdaneta', 'municipio_id' => 32],
      ['parroquia' => 'San Juan de Payara', 'municipio_id' => 33],
      ['parroquia' => 'Codazzi', 'municipio_id' => 33],
      ['parroquia' => 'Cunaviche', 'municipio_id' => 33],
      ['parroquia' => 'Elorza', 'municipio_id' => 34],
      ['parroquia' => 'La Trinidad', 'municipio_id' => 34],
      ['parroquia' => 'San Fernando', 'municipio_id' => 35],
      ['parroquia' => 'El Recreo', 'municipio_id' => 35],
      ['parroquia' => 'Peñalver', 'municipio_id' => 35],
      ['parroquia' => 'San Rafael de Atamaica', 'municipio_id' => 35],
      ['parroquia' => 'Bolívar', 'municipio_id' => 36],
      ['parroquia' => 'Camatagua', 'municipio_id' => 37],
      ['parroquia' => 'Carmen de Cura', 'municipio_id' => 37],
      ['parroquia' => 'Santa Rita', 'municipio_id' => 38],
      ['parroquia' => 'Francisco de Miranda', 'municipio_id' => 38],
      ['parroquia' => 'Moseñor Feliciano González', 'municipio_id' => 38],
      ['parroquia' => 'Pedro José Ovalles', 'municipio_id' => 39],
      ['parroquia' => 'Joaquín Crespo', 'municipio_id' => 39],
      ['parroquia' => 'José Casanova Godoy', 'municipio_id' => 39],
      ['parroquia' => 'Madre María de San José', 'municipio_id' => 39],
      ['parroquia' => 'Andrés Eloy Blanco', 'municipio_id' => 39],
      ['parroquia' => 'Los Tacarigua', 'municipio_id' => 39],
      ['parroquia' => 'Las Delicias', 'municipio_id' => 39],
      ['parroquia' => 'Choroní', 'municipio_id' => 39],
      ['parroquia' => 'Santa Cruz', 'municipio_id' => 40],
      ['parroquia' => 'José Félix Ribas', 'municipio_id' => 41],
      ['parroquia' => 'Castor Nieves Ríos', 'municipio_id' => 41],
      ['parroquia' => 'Las Guacamayas', 'municipio_id' => 41],
      ['parroquia' => 'Pao de Zárate', 'municipio_id' => 41],
      ['parroquia' => 'Zuata', 'municipio_id' => 41],
      ['parroquia' => 'José Rafael Revenga', 'municipio_id' => 42],
      ['parroquia' => 'Palo Negro', 'municipio_id' => 43],
      ['parroquia' => 'San Martín de Porres', 'municipio_id' => 43],
      ['parroquia' => 'El Limón', 'municipio_id' => 44],
      ['parroquia' => 'Caña de Azúcar', 'municipio_id' => 44],
      ['parroquia' => 'Ocumare de la Costa', 'municipio_id' => 45],
      ['parroquia' => 'San Casimiro', 'municipio_id' => 46],
      ['parroquia' => 'Güiripa', 'municipio_id' => 46],
      ['parroquia' => 'Ollas de Caramacate', 'municipio_id' => 46],
      ['parroquia' => 'Valle Morín', 'municipio_id' => 46],
      ['parroquia' => 'San Sebastián', 'municipio_id' => 47],
      ['parroquia' => 'Turmero', 'municipio_id' => 48],
      ['parroquia' => 'Arevalo Aponte', 'municipio_id' => 48],
      ['parroquia' => 'Chuao', 'municipio_id' => 48],
      ['parroquia' => 'Samán de Güere', 'municipio_id' => 48],
      ['parroquia' => 'Alfredo Pacheco Miranda', 'municipio_id' => 48],
      ['parroquia' => 'Santos Michelena', 'municipio_id' => 49],
      ['parroquia' => 'Tiara', 'municipio_id' => 49],
      ['parroquia' => 'Cagua', 'municipio_id' => 50],
      ['parroquia' => 'Bella Vista', 'municipio_id' => 50],
      ['parroquia' => 'Tovar', 'municipio_id' => 51],
      ['parroquia' => 'Urdaneta', 'municipio_id' => 52],
      ['parroquia' => 'Las Peñitas', 'municipio_id' => 52],
      ['parroquia' => 'San Francisco de Cara', 'municipio_id' => 52],
      ['parroquia' => 'Taguay', 'municipio_id' => 52],
      ['parroquia' => 'Zamora', 'municipio_id' => 53],
      ['parroquia' => 'Magdaleno', 'municipio_id' => 53],
      ['parroquia' => 'San Francisco de Asís', 'municipio_id' => 53],
      ['parroquia' => 'Valles de Tucutunemo', 'municipio_id' => 53],
      ['parroquia' => 'Augusto Mijares', 'municipio_id' => 53],
      ['parroquia' => 'Sabaneta', 'municipio_id' => 54],
      ['parroquia' => 'Juan Antonio Rodríguez Domínguez', 'municipio_id' => 54],
      ['parroquia' => 'El Cantón', 'municipio_id' => 55],
      ['parroquia' => 'Santa Cruz de Guacas', 'municipio_id' => 55],
      ['parroquia' => 'Puerto Vivas', 'municipio_id' => 55],
      ['parroquia' => 'Ticoporo', 'municipio_id' => 56],
      ['parroquia' => 'Nicolás Pulido', 'municipio_id' => 56],
      ['parroquia' => 'Andrés Bello', 'municipio_id' => 56],
      ['parroquia' => 'Arismendi', 'municipio_id' => 57],
      ['parroquia' => 'Guadarrama', 'municipio_id' => 57],
      ['parroquia' => 'La Unión', 'municipio_id' => 57],
      ['parroquia' => 'San Antonio', 'municipio_id' => 57],
      ['parroquia' => 'Barinas', 'municipio_id' => 58],
      ['parroquia' => 'Alberto Arvelo Larriva', 'municipio_id' => 58],
      ['parroquia' => 'San Silvestre', 'municipio_id' => 58],
      ['parroquia' => 'Santa Inés', 'municipio_id' => 58],
      ['parroquia' => 'Santa Lucía', 'municipio_id' => 58],
      ['parroquia' => 'Torunos', 'municipio_id' => 58],
      ['parroquia' => 'El Carmen', 'municipio_id' => 58],
      ['parroquia' => 'Rómulo Betancourt', 'municipio_id' => 58],
      ['parroquia' => 'Corazón de Jesús', 'municipio_id' => 58],
      ['parroquia' => 'Ramón Ignacio Méndez', 'municipio_id' => 58],
      ['parroquia' => 'Alto Barinas', 'municipio_id' => 58],
      ['parroquia' => 'Manuel Palacio Fajardo', 'municipio_id' => 58],
      ['parroquia' => 'Juan Antonio Rodríguez Domínguez', 'municipio_id' => 58],
      ['parroquia' => 'Dominga Ortiz de Páez', 'municipio_id' => 58],
      ['parroquia' => 'Barinitas', 'municipio_id' => 59],
      ['parroquia' => 'Altamira de Cáceres', 'municipio_id' => 59],
      ['parroquia' => 'Calderas', 'municipio_id' => 59],
      ['parroquia' => 'Barrancas', 'municipio_id' => 60],
      ['parroquia' => 'El Socorro', 'municipio_id' => 60],
      ['parroquia' => 'Mazparrito', 'municipio_id' => 60],
      ['parroquia' => 'Santa Bárbara', 'municipio_id' => 61],
      ['parroquia' => 'Pedro Briceño Méndez', 'municipio_id' => 61],
      ['parroquia' => 'Ramón Ignacio Méndez', 'municipio_id' => 61],
      ['parroquia' => 'José Ignacio del Pumar', 'municipio_id' => 61],
      ['parroquia' => 'Obispos', 'municipio_id' => 62],
      ['parroquia' => 'Los Guasimitos', 'municipio_id' => 62],
      ['parroquia' => 'El Real', 'municipio_id' => 62],
      ['parroquia' => 'La Luz', 'municipio_id' => 62],
      ['parroquia' => 'Ciudad Bolívia', 'municipio_id' => 63],
      ['parroquia' => 'José Ignacio Briceño', 'municipio_id' => 63],
      ['parroquia' => 'José Félix Ribas', 'municipio_id' => 63],
      ['parroquia' => 'Páez', 'municipio_id' => 63],
      ['parroquia' => 'Libertad', 'municipio_id' => 64],
      ['parroquia' => 'Dolores', 'municipio_id' => 64],
      ['parroquia' => 'Santa Rosa', 'municipio_id' => 64],
      ['parroquia' => 'Palacio Fajardo', 'municipio_id' => 64],
      ['parroquia' => 'Simón Rodríguez', 'municipio_id' => 64],
      ['parroquia' => 'Ciudad de Nutrias', 'municipio_id' => 65],
      ['parroquia' => 'El Regalo', 'municipio_id' => 65],
      ['parroquia' => 'Puerto Nutrias', 'municipio_id' => 65],
      ['parroquia' => 'Santa Catalina', 'municipio_id' => 65],
      ['parroquia' => 'Simón Bolívar', 'municipio_id' => 65],
      ['parroquia' => 'Raúl Leoni', 'municipio_id' => 66],
      ['parroquia' => 'Barceloneta', 'municipio_id' => 66],
      ['parroquia' => 'Santa Bárbara', 'municipio_id' => 66],
      ['parroquia' => 'San Francisco', 'municipio_id' => 66],
      ['parroquia' => 'Cachamay', 'municipio_id' => 67],
      ['parroquia' => 'Chirica', 'municipio_id' => 67],
      ['parroquia' => 'Dalla Costa', 'municipio_id' => 67],
      ['parroquia' => 'Once de Abril', 'municipio_id' => 67],
      ['parroquia' => 'Simón Bolívar', 'municipio_id' => 67],
      ['parroquia' => 'Unare', 'municipio_id' => 67],
      ['parroquia' => 'Universidad', 'municipio_id' => 67],
      ['parroquia' => 'Vista al Sol', 'municipio_id' => 67],
      ['parroquia' => 'Pozo Verde', 'municipio_id' => 67],
      ['parroquia' => 'Yocoima', 'municipio_id' => 67],
      ['parroquia' => '5 de Julio', 'municipio_id' => 67],
      ['parroquia' => 'Cedeño', 'municipio_id' => 68],
      ['parroquia' => 'Altagracia', 'municipio_id' => 68],
      ['parroquia' => 'Ascensión Farreras', 'municipio_id' => 68],
      ['parroquia' => 'Guaniamo', 'municipio_id' => 68],
      ['parroquia' => 'La Urbana', 'municipio_id' => 68],
      ['parroquia' => 'Pijiguaos', 'municipio_id' => 68],
      ['parroquia' => 'El Callao', 'municipio_id' => 69],
      ['parroquia' => 'Gran Sabana', 'municipio_id' => 70],
      ['parroquia' => 'Ikabarú', 'municipio_id' => 70],
      ['parroquia' => 'Catedral', 'municipio_id' => 71],
      ['parroquia' => 'Zea', 'municipio_id' => 71],
      ['parroquia' => 'Orinoco', 'municipio_id' => 71],
      ['parroquia' => 'José Antonio Páez', 'municipio_id' => 71],
      ['parroquia' => 'Marhuanta', 'municipio_id' => 71],
      ['parroquia' => 'Agua Salada', 'municipio_id' => 71],
      ['parroquia' => 'Vista Hermosa', 'municipio_id' => 71],
      ['parroquia' => 'La Sabanita', 'municipio_id' => 71],
      ['parroquia' => 'Panapana', 'municipio_id' => 71],
      ['parroquia' => 'Andrés Eloy Blanco', 'municipio_id' => 72],
      ['parroquia' => 'Pedro Cova', 'municipio_id' => 72],
      ['parroquia' => 'Roscio', 'municipio_id' => 73],
      ['parroquia' => 'Salóm', 'municipio_id' => 73],
      ['parroquia' => 'Sifontes', 'municipio_id' => 74],
      ['parroquia' => 'Dalla Costa', 'municipio_id' => 74],
      ['parroquia' => 'San Isidro', 'municipio_id' => 74],
      ['parroquia' => 'Sucre', 'municipio_id' => 75],
      ['parroquia' => 'Aripao', 'municipio_id' => 75],
      ['parroquia' => 'Guarataro', 'municipio_id' => 75],
      ['parroquia' => 'Las Majadas', 'municipio_id' => 75],
      ['parroquia' => 'Moitaco', 'municipio_id' => 75],
      ['parroquia' => 'Padre Pedro Chien', 'municipio_id' => 76],
      ['parroquia' => 'Río Grande', 'municipio_id' => 76],
      ['parroquia' => 'Bejuma', 'municipio_id' => 77],
      ['parroquia' => 'Canoabo', 'municipio_id' => 77],
      ['parroquia' => 'Simón Bolívar', 'municipio_id' => 77],
      ['parroquia' => 'Güigüe', 'municipio_id' => 78],
      ['parroquia' => 'Carabobo', 'municipio_id' => 78],
      ['parroquia' => 'Tacarigua', 'municipio_id' => 78],
      ['parroquia' => 'Mariara', 'municipio_id' => 79],
      ['parroquia' => 'Aguas Calientes', 'municipio_id' => 79],
      ['parroquia' => 'Ciudad Alianza', 'municipio_id' => 80],
      ['parroquia' => 'Guacara', 'municipio_id' => 80],
      ['parroquia' => 'Yagua', 'municipio_id' => 80],
      ['parroquia' => 'Morón', 'municipio_id' => 81],
      ['parroquia' => 'Urama', 'municipio_id' => 81],
      ['parroquia' => 'Valencia', 'municipio_id' => 82],
      ['parroquia' => 'Campo Carabobo', 'municipio_id' => 82],
      ['parroquia' => 'Los Guayos', 'municipio_id' => 83],
      ['parroquia' => 'Miranda', 'municipio_id' => 84],
      ['parroquia' => 'Montalbán', 'municipio_id' => 85],
      ['parroquia' => 'Naguanagua', 'municipio_id' => 86],
      ['parroquia' => 'Bartolomé Salóm', 'municipio_id' => 87],
      ['parroquia' => 'Democracia', 'municipio_id' => 87],
      ['parroquia' => 'Fraternidad', 'municipio_id' => 87],
      ['parroquia' => 'Goaigoaza', 'municipio_id' => 87],
      ['parroquia' => 'Juan José Flores', 'municipio_id' => 87],
      ['parroquia' => 'Unión', 'municipio_id' => 87],
      ['parroquia' => 'Borburata', 'municipio_id' => 87],
      ['parroquia' => 'Patanemo', 'municipio_id' => 87],
      ['parroquia' => 'San Diego', 'municipio_id' => 88],
      ['parroquia' => 'San Joaquín', 'municipio_id' => 89],
      ['parroquia' => 'Urbana Candelaria', 'municipio_id' => 90],
      ['parroquia' => 'Urbana Catedral', 'municipio_id' => 90],
      ['parroquia' => 'Urbana El Socorro', 'municipio_id' => 90],
      ['parroquia' => 'Urbana Miguel Peña', 'municipio_id' => 90],
      ['parroquia' => 'Urbana Rafael Urdaneta', 'municipio_id' => 90],
      ['parroquia' => 'Urbana San Blas', 'municipio_id' => 90],
      ['parroquia' => 'Urbana San José', 'municipio_id' => 90],
      ['parroquia' => 'Urbana Santa Rosa', 'municipio_id' => 90],
      ['parroquia' => 'No Urbana Negro Primero', 'municipio_id' => 90],
      ['parroquia' => 'Cojedes', 'municipio_id' => 91],
      ['parroquia' => 'Juan de Mata Suárez', 'municipio_id' => 91],
      ['parroquia' => 'Tinaquillo', 'municipio_id' => 92],
      ['parroquia' => 'El Baúl', 'municipio_id' => 93],
      ['parroquia' => 'Sucre', 'municipio_id' => 93],
      ['parroquia' => 'La Aguadita', 'municipio_id' => 94],
      ['parroquia' => 'Macapo', 'municipio_id' => 94],
      ['parroquia' => 'El Pao', 'municipio_id' => 95],
      ['parroquia' => 'El Amparo', 'municipio_id' => 96],
      ['parroquia' => 'Libertad de Cojedes', 'municipio_id' => 96],
      ['parroquia' => 'Rómulo Gallegos', 'municipio_id' => 97],
      ['parroquia' => 'San Carlos de Austria', 'municipio_id' => 98],
      ['parroquia' => 'Juan Ángel Bravo', 'municipio_id' => 98],
      ['parroquia' => 'Manuel Manrique', 'municipio_id' => 98],
      ['parroquia' => 'General en Jefe José Laurencio Silva', 'municipio_id' => 99],
      ['parroquia' => 'Curiapo', 'municipio_id' => 100],
      ['parroquia' => 'Almirante Luis Brión', 'municipio_id' => 100],
      ['parroquia' => 'Francisco Aniceto Lugo Boca de Cuyubini', 'municipio_id' => 100],
      ['parroquia' => 'Manuel Renaud', 'municipio_id' => 100],
      ['parroquia' => 'Padre Barral', 'municipio_id' => 100],
      ['parroquia' => 'Santos de Abelgas', 'municipio_id' => 100],
      ['parroquia' => 'Imataca Moruca', 'municipio_id' => 101],
      ['parroquia' => 'Cinco de Julio Piacoa', 'municipio_id' => 101],
      ['parroquia' => 'Juan Bautista Arismendi', 'municipio_id' => 101],
      ['parroquia' => 'Manuel Piar Santa Catalina', 'municipio_id' => 101],
      ['parroquia' => 'Rómulo Gallegos', 'municipio_id' => 101],
      ['parroquia' => 'Pedernales', 'municipio_id' => 102],
      ['parroquia' => 'Luis Beltrán Prieto Figueroa', 'municipio_id' => 102],
      ['parroquia' => 'San José', 'municipio_id' => 103],
      ['parroquia' => 'José Vidal Marcano Caparal de Guara', 'municipio_id' => 103],
      ['parroquia' => 'Juan Millán', 'municipio_id' => 103],
      ['parroquia' => 'Leonardo Ruíz Pineda Paloma', 'municipio_id' => 103],
      ['parroquia' => 'Mariscal Antonio José de Sucre', 'municipio_id' => 103],
      ['parroquia' => 'Monseñor Argimiro García San Rafael', 'municipio_id' => 103],
      ['parroquia' => 'San Rafael', 'municipio_id' => 103],
      ['parroquia' => 'Virgen del Valle', 'municipio_id' => 103],
      ['parroquia' => 'Capadare', 'municipio_id' => 104],
      ['parroquia' => 'La Pastora', 'municipio_id' => 104],
      ['parroquia' => 'Libertador', 'municipio_id' => 104],
      ['parroquia' => 'San Juan de los Cayos', 'municipio_id' => 104],
      ['parroquia' => 'Aracua', 'municipio_id' => 105],
      ['parroquia' => 'La Peña', 'municipio_id' => 105],
      ['parroquia' => 'San Luis', 'municipio_id' => 105],
      ['parroquia' => 'Bariro', 'municipio_id' => 106],
      ['parroquia' => 'Borojó', 'municipio_id' => 106],
      ['parroquia' => 'Capatárida', 'municipio_id' => 106],
      ['parroquia' => 'Guajiro', 'municipio_id' => 106],
      ['parroquia' => 'Seque', 'municipio_id' => 106],
      ['parroquia' => 'Zazárida', 'municipio_id' => 106],
      ['parroquia' => 'Valle de Eroa', 'municipio_id' => 106],
      ['parroquia' => 'Norte', 'municipio_id' => 107],
      ['parroquia' => 'Carirubana', 'municipio_id' => 107],
      ['parroquia' => 'Santa Ana', 'municipio_id' => 107],
      ['parroquia' => 'Urbana Punta Cardón', 'municipio_id' => 107],
      ['parroquia' => 'La Vela de Coro', 'municipio_id' => 108],
      ['parroquia' => 'Acurigua', 'municipio_id' => 108],
      ['parroquia' => 'Guaibacoa', 'municipio_id' => 108],
      ['parroquia' => 'Las Calderas', 'municipio_id' => 108],
      ['parroquia' => 'Macoruca', 'municipio_id' => 108],
      ['parroquia' => 'Dabajuro', 'municipio_id' => 109],
      ['parroquia' => 'Agua Clara', 'municipio_id' => 110],
      ['parroquia' => 'Avaria', 'municipio_id' => 110],
      ['parroquia' => 'Pedregal', 'municipio_id' => 110],
      ['parroquia' => 'Piedra Grande', 'municipio_id' => 110],
      ['parroquia' => 'Purureche', 'municipio_id' => 110],
      ['parroquia' => 'Adaure', 'municipio_id' => 111],
      ['parroquia' => 'Adícora', 'municipio_id' => 111],
      ['parroquia' => 'Baraived', 'municipio_id' => 111],
      ['parroquia' => 'Buena Vista', 'municipio_id' => 111],
      ['parroquia' => 'Jadacaquiva', 'municipio_id' => 111],
      ['parroquia' => 'El Vínculo', 'municipio_id' => 111],
      ['parroquia' => 'El Hato', 'municipio_id' => 111],
      ['parroquia' => 'Moruy', 'municipio_id' => 111],
      ['parroquia' => 'Pueblo Nuevo', 'municipio_id' => 111],
      ['parroquia' => 'Agua Larga', 'municipio_id' => 112],
      ['parroquia' => 'Churuguara', 'municipio_id' => 112],
      ['parroquia' => 'El Paují', 'municipio_id' => 112],
      ['parroquia' => 'Independencia', 'municipio_id' => 112],
      ['parroquia' => 'Mapararí', 'municipio_id' => 112],
      ['parroquia' => 'Agua Linda', 'municipio_id' => 113],
      ['parroquia' => 'Araurima', 'municipio_id' => 113],
      ['parroquia' => 'Jacura', 'municipio_id' => 113],
      ['parroquia' => 'Los Taques', 'municipio_id' => 114],
      ['parroquia' => 'Judibana', 'municipio_id' => 114],
      ['parroquia' => 'Cacique Manaure', 'municipio_id' => 115],
      ['parroquia' => 'Mene de Mauroa', 'municipio_id' => 116],
      ['parroquia' => 'San Félix', 'municipio_id' => 116],
      ['parroquia' => 'Casigua', 'municipio_id' => 116],
      ['parroquia' => 'Guzmán Guillermo', 'municipio_id' => 117],
      ['parroquia' => 'Mitare', 'municipio_id' => 117],
      ['parroquia' => 'Río Seco', 'municipio_id' => 117],
      ['parroquia' => 'Sabaneta', 'municipio_id' => 117],
      ['parroquia' => 'San Antonio', 'municipio_id' => 117],
      ['parroquia' => 'San Gabriel', 'municipio_id' => 117],
      ['parroquia' => 'Santa Ana', 'municipio_id' => 117],
      ['parroquia' => 'Boca del Tocuyo', 'municipio_id' => 118],
      ['parroquia' => 'Chichiriviche', 'municipio_id' => 118],
      ['parroquia' => 'Tocuyo de la Costa', 'municipio_id' => 118],
      ['parroquia' => 'Palmasola', 'municipio_id' => 119],
      ['parroquia' => 'Cabure', 'municipio_id' => 120],
      ['parroquia' => 'Colina', 'municipio_id' => 120],
      ['parroquia' => 'Curimagua', 'municipio_id' => 120],
      ['parroquia' => 'San José de la Costa', 'municipio_id' => 121],
      ['parroquia' => 'Píritu', 'municipio_id' => 121],
      ['parroquia' => 'Capital San Francisco', 'municipio_id' => 122],
      ['parroquia' => 'Sucre', 'municipio_id' => 123],
      ['parroquia' => 'Pecaya', 'municipio_id' => 123],
      ['parroquia' => 'Tucacas', 'municipio_id' => 124],
      ['parroquia' => 'Boca de Aroa', 'municipio_id' => 124],
      ['parroquia' => 'Tocópero', 'municipio_id' => 125],
      ['parroquia' => 'El Charal', 'municipio_id' => 126],
      ['parroquia' => 'Las Vegas del Tuy', 'municipio_id' => 126],
      ['parroquia' => 'Santa Cruz de Bucaral', 'municipio_id' => 126],
      ['parroquia' => 'Bruzual', 'municipio_id' => 127],
      ['parroquia' => 'Urumaco', 'municipio_id' => 127],
      ['parroquia' => 'Puerto Cumarebo', 'municipio_id' => 128],
      ['parroquia' => 'La Ciénaga', 'municipio_id' => 128],
      ['parroquia' => 'La Soledad', 'municipio_id' => 128],
      ['parroquia' => 'Pueblo Cumarebo', 'municipio_id' => 128],
      ['parroquia' => 'Zazárida', 'municipio_id' => 128],
      ['parroquia' => 'Camaguán', 'municipio_id' => 129],
      ['parroquia' => 'Puerto Miranda', 'municipio_id' => 129],
      ['parroquia' => 'Uverito', 'municipio_id' => 129],
      ['parroquia' => 'Chaguaramas', 'municipio_id' => 130],
      ['parroquia' => 'El Socorro', 'municipio_id' => 131],
      ['parroquia' => 'Valle de la Pascua', 'municipio_id' => 132],
      ['parroquia' => 'Espino', 'municipio_id' => 132],
      ['parroquia' => 'Las Mercedes', 'municipio_id' => 133],
      ['parroquia' => 'Cabruta', 'municipio_id' => 133],
      ['parroquia' => 'Santa Rita de Manapire', 'municipio_id' => 133],
      ['parroquia' => 'El Sombrero', 'municipio_id' => 134],
      ['parroquia' => 'Sosa', 'municipio_id' => 134],
      ['parroquia' => 'El Calvario', 'municipio_id' => 135],
      ['parroquia' => 'El Rastro', 'municipio_id' => 135],
      ['parroquia' => 'Guardatinajas', 'municipio_id' => 135],
      ['parroquia' => 'Capital Urbana Calabozo', 'municipio_id' => 135],
      ['parroquia' => 'Altagracia de Orituco', 'municipio_id' => 136],
      ['parroquia' => 'San Rafael de Orituco', 'municipio_id' => 136],
      ['parroquia' => 'San Francisco Javier de Lezama', 'municipio_id' => 136],
      ['parroquia' => 'Paso Real de Macaira', 'municipio_id' => 136],
      ['parroquia' => 'Carlos Soublette', 'municipio_id' => 136],
      ['parroquia' => 'San Francisco de Macaira', 'municipio_id' => 136],
      ['parroquia' => 'Libertad de Orituco', 'municipio_id' => 136],
      ['parroquia' => 'San José de Tiznados', 'municipio_id' => 137],
      ['parroquia' => 'San Francisco de Tiznados', 'municipio_id' => 137],
      ['parroquia' => 'San Lorenzo de Tiznados', 'municipio_id' => 137],
      ['parroquia' => 'Ortiz', 'municipio_id' => 137],
      ['parroquia' => 'Tucupido', 'municipio_id' => 138],
      ['parroquia' => 'San Rafael de Laya', 'municipio_id' => 138],
      ['parroquia' => 'Cantagallo', 'municipio_id' => 139],
      ['parroquia' => 'San Juan de los Morros', 'municipio_id' => 139],
      ['parroquia' => 'Parapara', 'municipio_id' => 139],
      ['parroquia' => 'Guayabal', 'municipio_id' => 140],
      ['parroquia' => 'Cazorla', 'municipio_id' => 140],
      ['parroquia' => 'San José de Guaribe', 'municipio_id' => 141],
      ['parroquia' => 'Uveral', 'municipio_id' => 141],
      ['parroquia' => 'Santa María de Ipire', 'municipio_id' => 142],
      ['parroquia' => 'Altamira', 'municipio_id' => 142],
      ['parroquia' => 'Unare', 'municipio_id' => 143],
      ['parroquia' => 'Zaraza', 'municipio_id' => 143],
      ['parroquia' => 'Quebrada Honda de Guache', 'municipio_id' => 144],
      ['parroquia' => 'Pío Tamayo', 'municipio_id' => 144],
      ['parroquia' => 'Yacambú', 'municipio_id' => 144],
      ['parroquia' => 'Freitez', 'municipio_id' => 145],
      ['parroquia' => 'José María Blanco', 'municipio_id' => 145],
      ['parroquia' => 'Catedral', 'municipio_id' => 146],
      ['parroquia' => 'Concepción', 'municipio_id' => 146],
      ['parroquia' => 'El Cují', 'municipio_id' => 146],
      ['parroquia' => 'Juan de Villegas', 'municipio_id' => 146],
      ['parroquia' => 'Santa Rosa', 'municipio_id' => 146],
      ['parroquia' => 'Tamaca', 'municipio_id' => 146],
      ['parroquia' => 'Unión', 'municipio_id' => 146],
      ['parroquia' => 'Aguedo Felipe Alvarado', 'municipio_id' => 146],
      ['parroquia' => 'Buena Vista', 'municipio_id' => 146],
      ['parroquia' => 'Juárez', 'municipio_id' => 146],
      ['parroquia' => 'Juan Bautista Rodríguez', 'municipio_id' => 147],
      ['parroquia' => 'Cuara', 'municipio_id' => 147],
      ['parroquia' => 'Diego de Lozada', 'municipio_id' => 147],
      ['parroquia' => 'Paraíso de San José', 'municipio_id' => 147],
      ['parroquia' => 'San Miguel', 'municipio_id' => 147],
      ['parroquia' => 'Tintorero', 'municipio_id' => 147],
      ['parroquia' => 'José Bernardo Dorante', 'municipio_id' => 147],
      ['parroquia' => 'Coronel Mariano Peraza', 'municipio_id' => 147],
      ['parroquia' => 'Anzoátegui', 'municipio_id' => 148],
      ['parroquia' => 'Bolívar', 'municipio_id' => 148],
      ['parroquia' => 'Guárico', 'municipio_id' => 148],
      ['parroquia' => 'Hilario Luna y Luna', 'municipio_id' => 148],
      ['parroquia' => 'Humocaro Bajo', 'municipio_id' => 148],
      ['parroquia' => 'Humocaro Alto', 'municipio_id' => 148],
      ['parroquia' => 'La Candelaria', 'municipio_id' => 148],
      ['parroquia' => 'Morán', 'municipio_id' => 148],
      ['parroquia' => 'Cabudare', 'municipio_id' => 149],
      ['parroquia' => 'José Gregorio Bastidas', 'municipio_id' => 149],
      ['parroquia' => 'Agua Viva', 'municipio_id' => 149],
      ['parroquia' => 'Buría', 'municipio_id' => 150],
      ['parroquia' => 'Gustavo Vega', 'municipio_id' => 150],
      ['parroquia' => 'Sarare', 'municipio_id' => 150],
      ['parroquia' => 'Altagracia', 'municipio_id' => 151],
      ['parroquia' => 'Antonio Díaz', 'municipio_id' => 151],
      ['parroquia' => 'Camacaro', 'municipio_id' => 151],
      ['parroquia' => 'Castañeda', 'municipio_id' => 151],
      ['parroquia' => 'Cecilio Zubillaga', 'municipio_id' => 151],
      ['parroquia' => 'Chiquinquira', 'municipio_id' => 151],
      ['parroquia' => 'El Blanco', 'municipio_id' => 151],
      ['parroquia' => 'Espinoza de los Monteros', 'municipio_id' => 151],
      ['parroquia' => 'Heriberto Arrollo', 'municipio_id' => 151],
      ['parroquia' => 'Lara', 'municipio_id' => 151],
      ['parroquia' => 'Las Mercedes', 'municipio_id' => 151],
      ['parroquia' => 'Manuel Morillo', 'municipio_id' => 151],
      ['parroquia' => 'Montaña Verde', 'municipio_id' => 151],
      ['parroquia' => 'Montes de Oca', 'municipio_id' => 151],
      ['parroquia' => 'Reyes de Vargas', 'municipio_id' => 151],
      ['parroquia' => 'Torres', 'municipio_id' => 151],
      ['parroquia' => 'Trinidad Samuel', 'municipio_id' => 151],
      ['parroquia' => 'Siquisique', 'municipio_id' => 152],
      ['parroquia' => 'San Miguel', 'municipio_id' => 152],
      ['parroquia' => 'Moroturo', 'municipio_id' => 152],
      ['parroquia' => 'Xaguas', 'municipio_id' => 152],
      ['parroquia' => 'Presidente Betancourt', 'municipio_id' => 153],
      ['parroquia' => 'Presidente Páez', 'municipio_id' => 153],
      ['parroquia' => 'Presidente Rómulo Gallegos', 'municipio_id' => 153],
      ['parroquia' => 'Gabriel Picón González', 'municipio_id' => 153],
      ['parroquia' => 'Héctor Amable Mora', 'municipio_id' => 153],
      ['parroquia' => 'José Nucete Sardi', 'municipio_id' => 153],
      ['parroquia' => 'Pulido Méndez', 'municipio_id' => 153],
      ['parroquia' => 'La Azulita', 'municipio_id' => 154],
      ['parroquia' => 'Santa Cruz de Mora', 'municipio_id' => 155],
      ['parroquia' => 'Mesa Bolívar', 'municipio_id' => 155],
      ['parroquia' => 'Mesa de Las Palmas', 'municipio_id' => 155],
      ['parroquia' => 'Aricagua', 'municipio_id' => 156],
      ['parroquia' => 'San Antonio', 'municipio_id' => 156],
      ['parroquia' => 'Canagua', 'municipio_id' => 157],
      ['parroquia' => 'Capurí', 'municipio_id' => 157],
      ['parroquia' => 'Chacantá', 'municipio_id' => 157],
      ['parroquia' => 'El Molino', 'municipio_id' => 157],
      ['parroquia' => 'Guaimaral', 'municipio_id' => 157],
      ['parroquia' => 'Mucutuy', 'municipio_id' => 157],
      ['parroquia' => 'Mucuchachí', 'municipio_id' => 157],
      ['parroquia' => 'Fernández Peña', 'municipio_id' => 158],
      ['parroquia' => 'Matriz', 'municipio_id' => 158],
      ['parroquia' => 'Montalbán', 'municipio_id' => 158],
      ['parroquia' => 'Acequias', 'municipio_id' => 158],
      ['parroquia' => 'Jají', 'municipio_id' => 158],
      ['parroquia' => 'La Mesa', 'municipio_id' => 158],
      ['parroquia' => 'San José del Sur', 'municipio_id' => 158],
      ['parroquia' => 'Tucaní', 'municipio_id' => 159],
      ['parroquia' => 'Florencio Ramírez', 'municipio_id' => 159],
      ['parroquia' => 'Santo Domingo', 'municipio_id' => 160],
      ['parroquia' => 'Las Piedras', 'municipio_id' => 160],
      ['parroquia' => 'Guaraque', 'municipio_id' => 161],
      ['parroquia' => 'Mesa de Quintero', 'municipio_id' => 161],
      ['parroquia' => 'Río Negro', 'municipio_id' => 161],
      ['parroquia' => 'Arapuey', 'municipio_id' => 162],
      ['parroquia' => 'Palmira', 'municipio_id' => 162],
      ['parroquia' => 'San Cristóbal de Torondoy', 'municipio_id' => 163],
      ['parroquia' => 'Torondoy', 'municipio_id' => 163],
      ['parroquia' => 'Antonio Spinetti Dini', 'municipio_id' => 164],
      ['parroquia' => 'Arias', 'municipio_id' => 164],
      ['parroquia' => 'Caracciolo Parra Pérez', 'municipio_id' => 164],
      ['parroquia' => 'Domingo Peña', 'municipio_id' => 164],
      ['parroquia' => 'El Llano', 'municipio_id' => 164],
      ['parroquia' => 'Gonzalo Picón Febres', 'municipio_id' => 164],
      ['parroquia' => 'Jacinto Plaza', 'municipio_id' => 164],
      ['parroquia' => 'Juan Rodríguez Suárez', 'municipio_id' => 164],
      ['parroquia' => 'Lasso de la Vega', 'municipio_id' => 164],
      ['parroquia' => 'Mariano Picón Salas', 'municipio_id' => 164],
      ['parroquia' => 'Milla', 'municipio_id' => 164],
      ['parroquia' => 'Osuna Rodríguez', 'municipio_id' => 164],
      ['parroquia' => 'Sagrario', 'municipio_id' => 164],
      ['parroquia' => 'El Morro', 'municipio_id' => 164],
      ['parroquia' => 'Los Nevados', 'municipio_id' => 164],
      ['parroquia' => 'Andrés Eloy Blanco', 'municipio_id' => 165],
      ['parroquia' => 'La Venta', 'municipio_id' => 165],
      ['parroquia' => 'Piñango', 'municipio_id' => 165],
      ['parroquia' => 'Timotes', 'municipio_id' => 165],
      ['parroquia' => 'Eloy Paredes', 'municipio_id' => 166],
      ['parroquia' => 'San Rafael de Alcázar', 'municipio_id' => 166],
      ['parroquia' => 'Santa Elena de Arenales', 'municipio_id' => 166],
      ['parroquia' => 'Santa María de Caparo', 'municipio_id' => 167],
      ['parroquia' => 'Pueblo Llano', 'municipio_id' => 168],
      ['parroquia' => 'Cacute', 'municipio_id' => 169],
      ['parroquia' => 'La Toma', 'municipio_id' => 169],
      ['parroquia' => 'Mucuchíes', 'municipio_id' => 169],
      ['parroquia' => 'Mucurubá', 'municipio_id' => 169],
      ['parroquia' => 'San Rafael', 'municipio_id' => 169],
      ['parroquia' => 'Gerónimo Maldonado', 'municipio_id' => 170],
      ['parroquia' => 'Bailadores', 'municipio_id' => 170],
      ['parroquia' => 'Tabay', 'municipio_id' => 171],
      ['parroquia' => 'Chiguará', 'municipio_id' => 172],
      ['parroquia' => 'Estánquez', 'municipio_id' => 172],
      ['parroquia' => 'Lagunillas', 'municipio_id' => 172],
      ['parroquia' => 'La Trampa', 'municipio_id' => 172],
      ['parroquia' => 'Pueblo Nuevo del Sur', 'municipio_id' => 172],
      ['parroquia' => 'San Juan', 'municipio_id' => 172],
      ['parroquia' => 'El Amparo', 'municipio_id' => 173],
      ['parroquia' => 'El Llano', 'municipio_id' => 173],
      ['parroquia' => 'San Francisco', 'municipio_id' => 173],
      ['parroquia' => 'Tovar', 'municipio_id' => 173],
      ['parroquia' => 'Independencia', 'municipio_id' => 174],
      ['parroquia' => 'María de la Concepción Palacios Blanco', 'municipio_id' => 174],
      ['parroquia' => 'Nueva Bolivia', 'municipio_id' => 174],
      ['parroquia' => 'Santa Apolonia', 'municipio_id' => 174],
      ['parroquia' => 'Caño El Tigre', 'municipio_id' => 175],
      ['parroquia' => 'Zea', 'municipio_id' => 175],
      ['parroquia' => 'Aragüita', 'municipio_id' => 176],
      ['parroquia' => 'Arévalo González', 'municipio_id' => 176],
      ['parroquia' => 'Capaya', 'municipio_id' => 176],
      ['parroquia' => 'Caucagua', 'municipio_id' => 176],
      ['parroquia' => 'Panaquire', 'municipio_id' => 176],
      ['parroquia' => 'Ribas', 'municipio_id' => 176],
      ['parroquia' => 'El Café', 'municipio_id' => 176],
      ['parroquia' => 'Marizapa', 'municipio_id' => 176],
      ['parroquia' => 'Cumbo', 'municipio_id' => 177],
      ['parroquia' => 'San José de Barlovento', 'municipio_id' => 177],
      ['parroquia' => 'El Cafetal', 'municipio_id' => 178],
      ['parroquia' => 'Las Minas', 'municipio_id' => 178],
      ['parroquia' => 'Nuestra Señora del Rosario', 'municipio_id' => 178],
      ['parroquia' => 'Higuerote', 'municipio_id' => 179],
      ['parroquia' => 'Curiepe', 'municipio_id' => 179],
      ['parroquia' => 'Tacarigua de Brión', 'municipio_id' => 179],
      ['parroquia' => 'Mamporal', 'municipio_id' => 180],
      ['parroquia' => 'Carrizal', 'municipio_id' => 181],
      ['parroquia' => 'Chacao', 'municipio_id' => 182],
      ['parroquia' => 'Charallave', 'municipio_id' => 183],
      ['parroquia' => 'Las Brisas', 'municipio_id' => 183],
      ['parroquia' => 'El Hatillo', 'municipio_id' => 184],
      ['parroquia' => 'Altagracia de la Montaña', 'municipio_id' => 185],
      ['parroquia' => 'Cecilio Acosta', 'municipio_id' => 185],
      ['parroquia' => 'Los Teques', 'municipio_id' => 185],
      ['parroquia' => 'El Jarillo', 'municipio_id' => 185],
      ['parroquia' => 'San Pedro.', 'municipio_id' => 185],
      ['parroquia' => 'Tácata', 'municipio_id' => 185],
      ['parroquia' => 'Paracotos', 'municipio_id' => 185],
      ['parroquia' => 'Cartanal', 'municipio_id' => 186],
      ['parroquia' => 'Santa Teresa del Tuy', 'municipio_id' => 186],
      ['parroquia' => 'La Democracia', 'municipio_id' => 187],
      ['parroquia' => 'Ocumare del Tuy', 'municipio_id' => 187],
      ['parroquia' => 'Santa Bárbara', 'municipio_id' => 187],
      ['parroquia' => 'San Antonio de los Altos', 'municipio_id' => 188],
      ['parroquia' => 'Río Chico', 'municipio_id' => 189],
      ['parroquia' => 'El Guapo', 'municipio_id' => 189],
      ['parroquia' => 'Tacarigua de la Laguna', 'municipio_id' => 189],
      ['parroquia' => 'Paparo', 'municipio_id' => 189],
      ['parroquia' => 'San Fernando del Guapo', 'municipio_id' => 189],
      ['parroquia' => 'Santa Lucía del Tuy', 'municipio_id' => 190],
      ['parroquia' => 'Cúpira', 'municipio_id' => 191],
      ['parroquia' => 'Machurucuto', 'municipio_id' => 191],
      ['parroquia' => 'Guarenas', 'municipio_id' => 192],
      ['parroquia' => 'San Antonio de Yare', 'municipio_id' => 193],
      ['parroquia' => 'San Francisco de Yare', 'municipio_id' => 193],
      ['parroquia' => 'Leoncio Martínez', 'municipio_id' => 194],
      ['parroquia' => 'Petare', 'municipio_id' => 194],
      ['parroquia' => 'Caucagüita', 'municipio_id' => 194],
      ['parroquia' => 'Filas de Mariche', 'municipio_id' => 194],
      ['parroquia' => 'La Dolorita', 'municipio_id' => 194],
      ['parroquia' => 'Cúa', 'municipio_id' => 195],
      ['parroquia' => 'Nueva Cúa', 'municipio_id' => 195],
      ['parroquia' => 'Guatire', 'municipio_id' => 196],
      ['parroquia' => 'Bolívar', 'municipio_id' => 196],
      ['parroquia' => 'San Antonio de Maturín', 'municipio_id' => 197],
      ['parroquia' => 'San Francisco de Maturín', 'municipio_id' => 197],
      ['parroquia' => 'Aguasay', 'municipio_id' => 198],
      ['parroquia' => 'Caripito', 'municipio_id' => 199],
      ['parroquia' => 'El Guácharo', 'municipio_id' => 200],
      ['parroquia' => 'La Guanota', 'municipio_id' => 200],
      ['parroquia' => 'Sabana de Piedra', 'municipio_id' => 200],
      ['parroquia' => 'San Agustín', 'municipio_id' => 200],
      ['parroquia' => 'Teresen', 'municipio_id' => 200],
      ['parroquia' => 'Caripe', 'municipio_id' => 200],
      ['parroquia' => 'Areo', 'municipio_id' => 201],
      ['parroquia' => 'Capital Cedeño', 'municipio_id' => 201],
      ['parroquia' => 'San Félix de Cantalicio', 'municipio_id' => 201],
      ['parroquia' => 'Viento Fresco', 'municipio_id' => 201],
      ['parroquia' => 'El Tejero', 'municipio_id' => 202],
      ['parroquia' => 'Punta de Mata', 'municipio_id' => 202],
      ['parroquia' => 'Chaguaramas', 'municipio_id' => 203],
      ['parroquia' => 'Las Alhuacas', 'municipio_id' => 203],
      ['parroquia' => 'Tabasca', 'municipio_id' => 203],
      ['parroquia' => 'Temblador', 'municipio_id' => 203],
      ['parroquia' => 'Alto de los Godos', 'municipio_id' => 204],
      ['parroquia' => 'Boquerón', 'municipio_id' => 204],
      ['parroquia' => 'Las Cocuizas', 'municipio_id' => 204],
      ['parroquia' => 'La Cruz', 'municipio_id' => 204],
      ['parroquia' => 'San Simón', 'municipio_id' => 204],
      ['parroquia' => 'El Corozo', 'municipio_id' => 204],
      ['parroquia' => 'El Furrial', 'municipio_id' => 204],
      ['parroquia' => 'Jusepín', 'municipio_id' => 204],
      ['parroquia' => 'La Pica', 'municipio_id' => 204],
      ['parroquia' => 'San Vicente', 'municipio_id' => 204],
      ['parroquia' => 'Aparicio', 'municipio_id' => 205],
      ['parroquia' => 'Aragua de Maturín', 'municipio_id' => 205],
      ['parroquia' => 'Chaguamal', 'municipio_id' => 205],
      ['parroquia' => 'El Pinto', 'municipio_id' => 205],
      ['parroquia' => 'Guanaguana', 'municipio_id' => 205],
      ['parroquia' => 'La Toscana', 'municipio_id' => 205],
      ['parroquia' => 'Taguaya', 'municipio_id' => 205],
      ['parroquia' => 'Cachipo', 'municipio_id' => 206],
      ['parroquia' => 'Quiriquire', 'municipio_id' => 206],
      ['parroquia' => 'Santa Bárbara', 'municipio_id' => 207],
      ['parroquia' => 'Barrancas', 'municipio_id' => 208],
      ['parroquia' => 'Los Barrancos de Fajardo', 'municipio_id' => 208],
      ['parroquia' => 'Uracoa', 'municipio_id' => 209],
      ['parroquia' => 'Antolín del Campo', 'municipio_id' => 210],
      ['parroquia' => 'Arismendi', 'municipio_id' => 211],
      ['parroquia' => 'San Juan Bautista', 'municipio_id' => 212],
      ['parroquia' => 'Zabala', 'municipio_id' => 212],
      ['parroquia' => 'García', 'municipio_id' => 213],
      ['parroquia' => 'Francisco Fajardo', 'municipio_id' => 213],
      ['parroquia' => 'Bolívar', 'municipio_id' => 214],
      ['parroquia' => 'Guevara', 'municipio_id' => 214],
      ['parroquia' => 'Cerro de Matasiete', 'municipio_id' => 214],
      ['parroquia' => 'Santa Ana', 'municipio_id' => 214],
      ['parroquia' => 'Sucre', 'municipio_id' => 214],
      ['parroquia' => 'Aguirre', 'municipio_id' => 215],
      ['parroquia' => 'Maneiro', 'municipio_id' => 215],
      ['parroquia' => 'Adrián', 'municipio_id' => 216],
      ['parroquia' => 'Juan Griego', 'municipio_id' => 216],
      ['parroquia' => 'Yaguaraparo', 'municipio_id' => 216],
      ['parroquia' => 'Porlamar', 'municipio_id' => 217],
      ['parroquia' => 'San Francisco de Macanao', 'municipio_id' => 218],
      ['parroquia' => 'Boca de Río', 'municipio_id' => 218],
      ['parroquia' => 'Tubores', 'municipio_id' => 219],
      ['parroquia' => 'Los Barales', 'municipio_id' => 219],
      ['parroquia' => 'Vicente Fuentes', 'municipio_id' => 220],
      ['parroquia' => 'Villalba', 'municipio_id' => 220],
      ['parroquia' => 'Agua Blanca', 'municipio_id' => 221],
      ['parroquia' => 'Araure', 'municipio_id' => 222],
      ['parroquia' => 'Río Acarigua', 'municipio_id' => 222],
      ['parroquia' => 'Píritu', 'municipio_id' => 223],
      ['parroquia' => 'Uveral', 'municipio_id' => 223],
      ['parroquia' => 'Cordova', 'municipio_id' => 224],
      ['parroquia' => 'Guanare', 'municipio_id' => 224],
      ['parroquia' => 'San José de la Montaña', 'municipio_id' => 224],
      ['parroquia' => 'San Juan de Guanaguanare', 'municipio_id' => 224],
      ['parroquia' => 'Virgen de Coromoto', 'municipio_id' => 224],
      ['parroquia' => 'Guanarito', 'municipio_id' => 225],
      ['parroquia' => 'Trinidad de la Capilla', 'municipio_id' => 225],
      ['parroquia' => 'Divina Pastora', 'municipio_id' => 225],
      ['parroquia' => 'Peña Blanca', 'municipio_id' => 226],
      ['parroquia' => 'Aparición', 'municipio_id' => 227],
      ['parroquia' => 'La Estación', 'municipio_id' => 227],
      ['parroquia' => 'Ospino', 'municipio_id' => 227],
      ['parroquia' => 'Acarigua', 'municipio_id' => 228],
      ['parroquia' => 'Payara', 'municipio_id' => 228],
      ['parroquia' => 'Pimpinela', 'municipio_id' => 228],
      ['parroquia' => 'Ramón Peraza', 'municipio_id' => 228],
      ['parroquia' => 'Caño Delgadito', 'municipio_id' => 229],
      ['parroquia' => 'Papelón', 'municipio_id' => 229],
      ['parroquia' => 'Antolín Tovar Anquino', 'municipio_id' => 230],
      ['parroquia' => 'Boconoíto', 'municipio_id' => 230],
      ['parroquia' => 'Santa Fé', 'municipio_id' => 231],
      ['parroquia' => 'San Rafael de Onoto', 'municipio_id' => 231],
      ['parroquia' => 'Thermo Morales', 'municipio_id' => 231],
      ['parroquia' => 'Florida', 'municipio_id' => 232],
      ['parroquia' => 'El Playón', 'municipio_id' => 232],
      ['parroquia' => 'Biscucuy', 'municipio_id' => 233],
      ['parroquia' => 'Concepción', 'municipio_id' => 233],
      ['parroquia' => 'San José de Saguaz', 'municipio_id' => 233],
      ['parroquia' => 'San Rafael de Palo Alzado', 'municipio_id' => 233],
      ['parroquia' => 'Uvencio Antonio Velásquez', 'municipio_id' => 233],
      ['parroquia' => 'Villa Rosa', 'municipio_id' => 233],
      ['parroquia' => 'Canelones', 'municipio_id' => 234],
      ['parroquia' => 'Santa Cruz', 'municipio_id' => 234],
      ['parroquia' => 'San Isidro Labrador', 'municipio_id' => 234],
      ['parroquia' => 'Mariño', 'municipio_id' => 235],
      ['parroquia' => 'Rómulo Gallegos', 'municipio_id' => 235],
      ['parroquia' => 'San José de Aerocuar', 'municipio_id' => 236],
      ['parroquia' => 'Tavera Acosta', 'municipio_id' => 236],
      ['parroquia' => 'Río Caribe', 'municipio_id' => 237],
      ['parroquia' => 'Antonio José de Sucre', 'municipio_id' => 237],
      ['parroquia' => 'El Morro de Puerto Santo', 'municipio_id' => 237],
      ['parroquia' => 'Puerto Santo', 'municipio_id' => 237],
      ['parroquia' => 'San Juan de las Galdonas', 'municipio_id' => 237],
      ['parroquia' => 'El Pilar', 'municipio_id' => 238],
      ['parroquia' => 'El Rincón', 'municipio_id' => 238],
      ['parroquia' => 'General Francisco Antonio Váquez', 'municipio_id' => 238],
      ['parroquia' => 'Guaraúnos', 'municipio_id' => 238],
      ['parroquia' => 'Tunapuicito', 'municipio_id' => 238],
      ['parroquia' => 'Unión', 'municipio_id' => 238],
      ['parroquia' => 'Santa Catalina', 'municipio_id' => 239],
      ['parroquia' => 'Santa Rosa', 'municipio_id' => 239],
      ['parroquia' => 'Santa Teresa', 'municipio_id' => 239],
      ['parroquia' => 'Bolívar', 'municipio_id' => 239],
      ['parroquia' => 'Maracapana', 'municipio_id' => 239],
      ['parroquia' => 'Libertad', 'municipio_id' => 241],
      ['parroquia' => 'El Paujil', 'municipio_id' => 241],
      ['parroquia' => 'Yaguaraparo', 'municipio_id' => 241],
      ['parroquia' => 'Cruz Salmerón Acosta', 'municipio_id' => 242],
      ['parroquia' => 'Chacopata', 'municipio_id' => 242],
      ['parroquia' => 'Manicuare', 'municipio_id' => 242],
      ['parroquia' => 'Tunapuy', 'municipio_id' => 243],
      ['parroquia' => 'Campo Elías', 'municipio_id' => 243],
      ['parroquia' => 'Irapa', 'municipio_id' => 244],
      ['parroquia' => 'Campo Claro', 'municipio_id' => 244],
      ['parroquia' => 'Maraval', 'municipio_id' => 244],
      ['parroquia' => 'San Antonio de Irapa', 'municipio_id' => 244],
      ['parroquia' => 'Soro', 'municipio_id' => 244],
      ['parroquia' => 'Mejía', 'municipio_id' => 245],
      ['parroquia' => 'Cumanacoa', 'municipio_id' => 246],
      ['parroquia' => 'Arenas', 'municipio_id' => 246],
      ['parroquia' => 'Aricagua', 'municipio_id' => 246],
      ['parroquia' => 'Cocollar', 'municipio_id' => 246],
      ['parroquia' => 'San Fernando', 'municipio_id' => 246],
      ['parroquia' => 'San Lorenzo', 'municipio_id' => 246],
      ['parroquia' => 'Villa Frontado (Muelle de Cariaco)', 'municipio_id' => 247],
      ['parroquia' => 'Catuaro', 'municipio_id' => 247],
      ['parroquia' => 'Rendón', 'municipio_id' => 247],
      ['parroquia' => 'San Cruz', 'municipio_id' => 247],
      ['parroquia' => 'Santa María', 'municipio_id' => 247],
      ['parroquia' => 'Altagracia Cumaná', 'municipio_id' => 248],
      ['parroquia' => 'Santa Inés Cumaná', 'municipio_id' => 248],
      ['parroquia' => 'Valentín Valiente Cumaná', 'municipio_id' => 248],
      ['parroquia' => 'Ayacucho Cumaná', 'municipio_id' => 248],
      ['parroquia' => 'San Juan', 'municipio_id' => 248],
      ['parroquia' => 'Raúl Leoni', 'municipio_id' => 248],
      ['parroquia' => 'Gran Mariscal', 'municipio_id' => 248],
      ['parroquia' => 'Cristóbal Colón', 'municipio_id' => 249],
      ['parroquia' => 'Bideau', 'municipio_id' => 249],
      ['parroquia' => 'Punta de Piedras', 'municipio_id' => 249],
      ['parroquia' => 'Güiria', 'municipio_id' => 249],
      ['parroquia' => 'Andrés Bello', 'municipio_id' => 250],
      ['parroquia' => 'Antonio Rómulo Costa', 'municipio_id' => 251],
      ['parroquia' => 'Ayacucho', 'municipio_id' => 252],
      ['parroquia' => 'Rivas Berti', 'municipio_id' => 252],
      ['parroquia' => 'San Pedro del Río', 'municipio_id' => 252],
      ['parroquia' => 'Bolívar', 'municipio_id' => 253],
      ['parroquia' => 'Palotal', 'municipio_id' => 253],
      ['parroquia' => 'General Juan Vicente Gómez', 'municipio_id' => 253],
      ['parroquia' => 'Isaías Medina Angarita', 'municipio_id' => 253],
      ['parroquia' => 'Cárdenas', 'municipio_id' => 254],
      ['parroquia' => 'Amenodoro Rangel Lamus', 'municipio_id' => 254],
      ['parroquia' => 'La Florida', 'municipio_id' => 254],
      ['parroquia' => 'Córdoba', 'municipio_id' => 255],
      ['parroquia' => 'Fernández Feo', 'municipio_id' => 256],
      ['parroquia' => 'Alberto Adriani', 'municipio_id' => 256],
      ['parroquia' => 'Santo Domingo', 'municipio_id' => 256],
      ['parroquia' => 'Francisco de Miranda', 'municipio_id' => 257],
      ['parroquia' => 'García de Hevia', 'municipio_id' => 258],
      ['parroquia' => 'Boca de Grita', 'municipio_id' => 258],
      ['parroquia' => 'José Antonio Páez', 'municipio_id' => 258],
      ['parroquia' => 'Guásimos', 'municipio_id' => 259],
      ['parroquia' => 'Independencia', 'municipio_id' => 260],
      ['parroquia' => 'Juan Germán Roscio', 'municipio_id' => 260],
      ['parroquia' => 'Román Cárdenas', 'municipio_id' => 260],
      ['parroquia' => 'Jáuregui', 'municipio_id' => 261],
      ['parroquia' => 'Emilio Constantino Guerrero', 'municipio_id' => 261],
      ['parroquia' => 'Monseñor Miguel Antonio Salas', 'municipio_id' => 261],
      ['parroquia' => 'José María Vargas', 'municipio_id' => 262],
      ['parroquia' => 'Junín', 'municipio_id' => 263],
      ['parroquia' => 'La Petrólea', 'municipio_id' => 263],
      ['parroquia' => 'Quinimarí', 'municipio_id' => 263],
      ['parroquia' => 'Bramón', 'municipio_id' => 263],
      ['parroquia' => 'Libertad', 'municipio_id' => 264],
      ['parroquia' => 'Cipriano Castro', 'municipio_id' => 264],
      ['parroquia' => 'Manuel Felipe Rugeles', 'municipio_id' => 264],
      ['parroquia' => 'Capital Libertador', 'municipio_id' => 265],
      ['parroquia' => 'Doradas', 'municipio_id' => 265],
      ['parroquia' => 'Emeterio Ochoa', 'municipio_id' => 265],
      ['parroquia' => 'San Joaquín de Navay', 'municipio_id' => 265],
      ['parroquia' => 'Lobatera', 'municipio_id' => 266],
      ['parroquia' => 'Constitución', 'municipio_id' => 266],
      ['parroquia' => 'Michelena', 'municipio_id' => 267],
      ['parroquia' => 'Panamericano', 'municipio_id' => 268],
      ['parroquia' => 'La Palmita', 'municipio_id' => 268],
      ['parroquia' => 'Pedro María Ureña', 'municipio_id' => 269],
      ['parroquia' => 'Nueva Arcadia', 'municipio_id' => 269],
      ['parroquia' => 'Delicias', 'municipio_id' => 270],
      ['parroquia' => 'Pecaya', 'municipio_id' => 270],
      ['parroquia' => 'Samuel Darío Maldonado', 'municipio_id' => 271],
      ['parroquia' => 'Boconó', 'municipio_id' => 271],
      ['parroquia' => 'Hernández', 'municipio_id' => 271],
      ['parroquia' => 'La Concordia', 'municipio_id' => 272],
      ['parroquia' => 'San Juan Bautista', 'municipio_id' => 272],
      ['parroquia' => 'Pedro María Morantes', 'municipio_id' => 272],
      ['parroquia' => 'San Sebastián', 'municipio_id' => 272],
      ['parroquia' => 'Dr. Francisco Romero Lobo', 'municipio_id' => 272],
      ['parroquia' => 'Seboruco', 'municipio_id' => 273],
      ['parroquia' => 'Simón Rodríguez', 'municipio_id' => 274],
      ['parroquia' => 'Sucre', 'municipio_id' => 275],
      ['parroquia' => 'Eleazar López Contreras', 'municipio_id' => 275],
      ['parroquia' => 'San Pablo', 'municipio_id' => 275],
      ['parroquia' => 'San José Obrero', 'municipio_id' => 276],
      ['parroquia' => 'San Juan Eudes', 'municipio_id' => 276],
      ['parroquia' => 'Uribante', 'municipio_id' => 277],
      ['parroquia' => 'Cárdenas', 'municipio_id' => 277],
      ['parroquia' => 'Juan Pablo Peñalosa', 'municipio_id' => 277],
      ['parroquia' => 'Potosí', 'municipio_id' => 277],
      ['parroquia' => 'San Judas Tadeo', 'municipio_id' => 278],
      ['parroquia' => 'Araguaney', 'municipio_id' => 279],
      ['parroquia' => 'El Jaguito', 'municipio_id' => 279],
      ['parroquia' => 'La Esperanza', 'municipio_id' => 279],
      ['parroquia' => 'Santa Isabel', 'municipio_id' => 279],
      ['parroquia' => 'Boconó', 'municipio_id' => 280],
      ['parroquia' => 'El Carmen', 'municipio_id' => 280],
      ['parroquia' => 'Mosquey', 'municipio_id' => 280],
      ['parroquia' => 'Ayacucho', 'municipio_id' => 280],
      ['parroquia' => 'Burbusay', 'municipio_id' => 280],
      ['parroquia' => 'General Ribas', 'municipio_id' => 280],
      ['parroquia' => 'Guaramacal', 'municipio_id' => 280],
      ['parroquia' => 'Vega de Guaramacal', 'municipio_id' => 280],
      ['parroquia' => 'Monseñor Jáuregui', 'municipio_id' => 280],
      ['parroquia' => 'Rafael Rangel', 'municipio_id' => 280],
      ['parroquia' => 'San Miguel', 'municipio_id' => 280],
      ['parroquia' => 'San José', 'municipio_id' => 280],
      ['parroquia' => 'Sabana Grande', 'municipio_id' => 281],
      ['parroquia' => 'Cheregüé', 'municipio_id' => 281],
      ['parroquia' => 'Granados', 'municipio_id' => 281],
      ['parroquia' => 'Arnoldo Gabaldón', 'municipio_id' => 282],
      ['parroquia' => 'Bolivia', 'municipio_id' => 282],
      ['parroquia' => 'Carrillo', 'municipio_id' => 282],
      ['parroquia' => 'Cegarra', 'municipio_id' => 282],
      ['parroquia' => 'Chejendé', 'municipio_id' => 282],
      ['parroquia' => 'Manuel Salvador Ulloa', 'municipio_id' => 282],
      ['parroquia' => 'San José', 'municipio_id' => 282],
      ['parroquia' => 'Carache', 'municipio_id' => 283],
      ['parroquia' => 'La Concepción', 'municipio_id' => 283],
      ['parroquia' => 'Cuicas', 'municipio_id' => 283],
      ['parroquia' => 'Panamericana', 'municipio_id' => 283],
      ['parroquia' => 'Santa Cruz', 'municipio_id' => 283],
      ['parroquia' => 'Escuque', 'municipio_id' => 284],
      ['parroquia' => 'La Unión (El Alto Escuque)', 'municipio_id' => 284],
      ['parroquia' => 'Santa Rita', 'municipio_id' => 284],
      ['parroquia' => 'Sabana Libre', 'municipio_id' => 284],
      ['parroquia' => 'El Socorro', 'municipio_id' => 285],
      ['parroquia' => 'Los Caprichos', 'municipio_id' => 285],
      ['parroquia' => 'Antonio José de Sucre', 'municipio_id' => 285],
      ['parroquia' => 'Campo Elías', 'municipio_id' => 286],
      ['parroquia' => 'Arnoldo Gabaldón', 'municipio_id' => 286],
      ['parroquia' => 'Santa Apolonia', 'municipio_id' => 287],
      ['parroquia' => 'El Progreso', 'municipio_id' => 287],
      ['parroquia' => 'La Ceiba', 'municipio_id' => 287],
      ['parroquia' => 'Tres de Febrero', 'municipio_id' => 287],
      ['parroquia' => 'El Dividive', 'municipio_id' => 288],
      ['parroquia' => 'Agua Santa', 'municipio_id' => 288],
      ['parroquia' => 'Agua Caliente', 'municipio_id' => 288],
      ['parroquia' => 'El Cenizo', 'municipio_id' => 288],
      ['parroquia' => 'Valerita', 'municipio_id' => 288],
      ['parroquia' => 'Monte Carmelo', 'municipio_id' => 289],
      ['parroquia' => 'Buena Vista', 'municipio_id' => 289],
      ['parroquia' => 'Santa María del Horcón', 'municipio_id' => 289],
      ['parroquia' => 'Motatán', 'municipio_id' => 290],
      ['parroquia' => 'El Baño', 'municipio_id' => 290],
      ['parroquia' => 'Jalisco', 'municipio_id' => 290],
      ['parroquia' => 'Pampán', 'municipio_id' => 291],
      ['parroquia' => 'Flor de Patria', 'municipio_id' => 291],
      ['parroquia' => 'La Paz', 'municipio_id' => 291],
      ['parroquia' => 'Santa Ana', 'municipio_id' => 291],
      ['parroquia' => 'Pampanito', 'municipio_id' => 292],
      ['parroquia' => 'La Concepción', 'municipio_id' => 292],
      ['parroquia' => 'Pampanito II', 'municipio_id' => 292],
      ['parroquia' => 'Betijoque', 'municipio_id' => 293],
      ['parroquia' => 'José Gregorio Hernández', 'municipio_id' => 293],
      ['parroquia' => 'La Pueblita', 'municipio_id' => 293],
      ['parroquia' => 'Los Cedros', 'municipio_id' => 293],
      ['parroquia' => 'Carvajal', 'municipio_id' => 294],
      ['parroquia' => 'Campo Alegre', 'municipio_id' => 294],
      ['parroquia' => 'Antonio Nicolás Briceño', 'municipio_id' => 294],
      ['parroquia' => 'José Leonardo Suárez', 'municipio_id' => 294],
      ['parroquia' => 'Sabana de Mendoza', 'municipio_id' => 295],
      ['parroquia' => 'Junín', 'municipio_id' => 295],
      ['parroquia' => 'Valmore Rodríguez', 'municipio_id' => 295],
      ['parroquia' => 'El Paraíso', 'municipio_id' => 295],
      ['parroquia' => 'Andrés Linares', 'municipio_id' => 296],
      ['parroquia' => 'Chiquinquirá', 'municipio_id' => 296],
      ['parroquia' => 'Cristóbal Mendoza', 'municipio_id' => 296],
      ['parroquia' => 'Cruz Carrillo', 'municipio_id' => 296],
      ['parroquia' => 'Matriz', 'municipio_id' => 296],
      ['parroquia' => 'Monseñor Carrillo', 'municipio_id' => 296],
      ['parroquia' => 'Tres Esquinas', 'municipio_id' => 296],
      ['parroquia' => 'Cabimbú', 'municipio_id' => 297],
      ['parroquia' => 'Jajó', 'municipio_id' => 297],
      ['parroquia' => 'La Mesa de Esnujaque', 'municipio_id' => 297],
      ['parroquia' => 'Santiago', 'municipio_id' => 297],
      ['parroquia' => 'Tuñame', 'municipio_id' => 297],
      ['parroquia' => 'La Quebrada', 'municipio_id' => 297],
      ['parroquia' => 'Juan Ignacio Montilla', 'municipio_id' => 298],
      ['parroquia' => 'La Beatriz', 'municipio_id' => 298],
      ['parroquia' => 'La Puerta', 'municipio_id' => 298],
      ['parroquia' => 'Mendoza del Valle de Momboy', 'municipio_id' => 298],
      ['parroquia' => 'Mercedes Díaz', 'municipio_id' => 298],
      ['parroquia' => 'San Luis', 'municipio_id' => 298],
      ['parroquia' => 'Caraballeda', 'municipio_id' => 299],
      ['parroquia' => 'Carayaca', 'municipio_id' => 299],
      ['parroquia' => 'Carlos Soublette', 'municipio_id' => 299],
      ['parroquia' => 'Caruao Chuspa', 'municipio_id' => 299],
      ['parroquia' => 'Catia La Mar', 'municipio_id' => 299],
      ['parroquia' => 'El Junko', 'municipio_id' => 299],
      ['parroquia' => 'La Guaira', 'municipio_id' => 299],
      ['parroquia' => 'Macuto', 'municipio_id' => 299],
      ['parroquia' => 'Maiquetía', 'municipio_id' => 299],
      ['parroquia' => 'Naiguatá', 'municipio_id' => 299],
      ['parroquia' => 'Urimare', 'municipio_id' => 299],
      ['parroquia' => 'Arístides Bastidas', 'municipio_id' => 300],
      ['parroquia' => 'Bolívar', 'municipio_id' => 301],
      ['parroquia' => 'Chivacoa', 'municipio_id' => 302],
      ['parroquia' => 'Campo Elías', 'municipio_id' => 302],
      ['parroquia' => 'Cocorote', 'municipio_id' => 303],
      ['parroquia' => 'Independencia', 'municipio_id' => 304],
      ['parroquia' => 'José Antonio Páez', 'municipio_id' => 305],
      ['parroquia' => 'La Trinidad', 'municipio_id' => 306],
      ['parroquia' => 'Manuel Monge', 'municipio_id' => 307],
      ['parroquia' => 'Salóm', 'municipio_id' => 308],
      ['parroquia' => 'Temerla', 'municipio_id' => 308],
      ['parroquia' => 'Nirgua', 'municipio_id' => 308],
      ['parroquia' => 'San Andrés', 'municipio_id' => 309],
      ['parroquia' => 'Yaritagua', 'municipio_id' => 309],
      ['parroquia' => 'San Javier', 'municipio_id' => 310],
      ['parroquia' => 'Albarico', 'municipio_id' => 310],
      ['parroquia' => 'San Felipe', 'municipio_id' => 310],
      ['parroquia' => 'Sucre', 'municipio_id' => 311],
      ['parroquia' => 'Urachiche', 'municipio_id' => 312],
      ['parroquia' => 'El Guayabo', 'municipio_id' => 313],
      ['parroquia' => 'Farriar', 'municipio_id' => 313],
      ['parroquia' => 'Isla de Toas', 'municipio_id' => 314],
      ['parroquia' => 'Monagas', 'municipio_id' => 314],
      ['parroquia' => 'General Urdaneta', 'municipio_id' => 315],
      ['parroquia' => 'Libertador', 'municipio_id' => 315],
      ['parroquia' => 'Marcelino Briceño', 'municipio_id' => 315],
      ['parroquia' => 'Pueblo Nuevo', 'municipio_id' => 315],
      ['parroquia' => 'Manuel Guanipa Matos', 'municipio_id' => 315],
      ['parroquia' => 'Ambrosio', 'municipio_id' => 316],
      ['parroquia' => 'Carmen Herrera', 'municipio_id' => 316],
      ['parroquia' => 'La Rosa', 'municipio_id' => 316],
      ['parroquia' => 'Germán Ríos Linares', 'municipio_id' => 316],
      ['parroquia' => 'San Benito', 'municipio_id' => 316],
      ['parroquia' => 'Rómulo Betancourt', 'municipio_id' => 316],
      ['parroquia' => 'Jorge Hernández', 'municipio_id' => 316],
      ['parroquia' => 'Punta Gorda', 'municipio_id' => 316],
      ['parroquia' => 'Arístides Calvani', 'municipio_id' => 316],
      ['parroquia' => 'Encontrados', 'municipio_id' => 317],
      ['parroquia' => 'Udón Pérez', 'municipio_id' => 317],
      ['parroquia' => 'Moralito', 'municipio_id' => 318],
      ['parroquia' => 'San Carlos del Zulia', 'municipio_id' => 318],
      ['parroquia' => 'Santa Cruz del Zulia', 'municipio_id' => 318],
      ['parroquia' => 'Santa Bárbara', 'municipio_id' => 318],
      ['parroquia' => 'Urribarrí', 'municipio_id' => 318],
      ['parroquia' => 'Carlos Quevedo', 'municipio_id' => 319],
      ['parroquia' => 'Francisco Javier Pulgar', 'municipio_id' => 319],
      ['parroquia' => 'Simón Rodríguez', 'municipio_id' => 319],
      ['parroquia' => 'Guamo-Gavilanes', 'municipio_id' => 319],
      ['parroquia' => 'Sinamaica', 'municipio_id' => 320],
      ['parroquia' => 'Alta Guajira', 'municipio_id' => 320],
      ['parroquia' => 'Elías Sánchez Rubio', 'municipio_id' => 320],
      ['parroquia' => 'Guajira', 'municipio_id' => 320],
      ['parroquia' => 'La Concepción', 'municipio_id' => 321],
      ['parroquia' => 'San José', 'municipio_id' => 321],
      ['parroquia' => 'Mariano Parra León', 'municipio_id' => 321],
      ['parroquia' => 'José Ramón Yépez', 'municipio_id' => 321],
      ['parroquia' => 'Jesús María Semprún', 'municipio_id' => 322],
      ['parroquia' => 'Barí', 'municipio_id' => 322],
      ['parroquia' => 'Concepción', 'municipio_id' => 323],
      ['parroquia' => 'Andrés Bello', 'municipio_id' => 323],
      ['parroquia' => 'Chiquinquirá', 'municipio_id' => 323],
      ['parroquia' => 'El Carmelo', 'municipio_id' => 323],
      ['parroquia' => 'Potreritos', 'municipio_id' => 323],
      ['parroquia' => 'Libertad', 'municipio_id' => 324],
      ['parroquia' => 'Alonso de Ojeda', 'municipio_id' => 324],
      ['parroquia' => 'Venezuela', 'municipio_id' => 324],
      ['parroquia' => 'Eleazar López Contreras', 'municipio_id' => 324],
      ['parroquia' => 'Campo Lara', 'municipio_id' => 324],
      ['parroquia' => 'Bartolomé de las Casas', 'municipio_id' => 325],
      ['parroquia' => 'Libertad', 'municipio_id' => 325],
      ['parroquia' => 'Río Negro', 'municipio_id' => 325],
      ['parroquia' => 'San José de Perijá', 'municipio_id' => 325],
      ['parroquia' => 'San Rafael', 'municipio_id' => 326],
      ['parroquia' => 'La Sierrita', 'municipio_id' => 326],
      ['parroquia' => 'Las Parcelas', 'municipio_id' => 326],
      ['parroquia' => 'Luis de Vicente', 'municipio_id' => 326],
      ['parroquia' => 'Monseñor Marcos Sergio Godoy', 'municipio_id' => 326],
      ['parroquia' => 'Ricaurte', 'municipio_id' => 326],
      ['parroquia' => 'Tamare', 'municipio_id' => 326],
      ['parroquia' => 'Antonio Borjas Romero', 'municipio_id' => 327],
      ['parroquia' => 'Bolívar', 'municipio_id' => 327],
      ['parroquia' => 'Cacique Mara', 'municipio_id' => 327],
      ['parroquia' => 'Carracciolo Parra Pérez', 'municipio_id' => 327],
      ['parroquia' => 'Cecilio Acosta', 'municipio_id' => 327],
      ['parroquia' => 'Cristo de Aranza', 'municipio_id' => 327],
      ['parroquia' => 'Coquivacoa', 'municipio_id' => 327],
      ['parroquia' => 'Chiquinquirá', 'municipio_id' => 327],
      ['parroquia' => 'Francisco Eugenio Bustamante', 'municipio_id' => 327],
      ['parroquia' => 'Idelfonzo Vásquez', 'municipio_id' => 327],
      ['parroquia' => 'Juana de Ávila', 'municipio_id' => 327],
      ['parroquia' => 'Luis Hurtado Higuera', 'municipio_id' => 327],
      ['parroquia' => 'Manuel Dagnino', 'municipio_id' => 327],
      ['parroquia' => 'Olegario Villalobos.', 'municipio_id' => 327],
      ['parroquia' => 'Raúl Leoni', 'municipio_id' => 327],
      ['parroquia' => 'Santa Lucía', 'municipio_id' => 327],
      ['parroquia' => 'Venancio Pulgar', 'municipio_id' => 327],
      ['parroquia' => 'San Isidro', 'municipio_id' => 327],
      ['parroquia' => 'Altagracia', 'municipio_id' => 328],
      ['parroquia' => 'Faría', 'municipio_id' => 328],
      ['parroquia' => 'Ana María Campos', 'municipio_id' => 328],
      ['parroquia' => 'San Antonio', 'municipio_id' => 328],
      ['parroquia' => 'San José', 'municipio_id' => 328],
      ['parroquia' => 'Donaldo García', 'municipio_id' => 329],
      ['parroquia' => 'El Rosario', 'municipio_id' => 329],
      ['parroquia' => 'Sixto Zambrano', 'municipio_id' => 329],
      ['parroquia' => 'San Francisco', 'municipio_id' => 330],
      ['parroquia' => 'El Bajo', 'municipio_id' => 330],
      ['parroquia' => 'Domitila Flores', 'municipio_id' => 330],
      ['parroquia' => 'Francisco Ochoa', 'municipio_id' => 330],
      ['parroquia' => 'Los Cortijos', 'municipio_id' => 330],
      ['parroquia' => 'Marcial Hernández', 'municipio_id' => 330],
      ['parroquia' => 'Santa Rita', 'municipio_id' => 331],
      ['parroquia' => 'El Mene', 'municipio_id' => 331],
      ['parroquia' => 'Pedro Lucas Urribarrí', 'municipio_id' => 331],
      ['parroquia' => 'José Cenobio Urribarrí', 'municipio_id' => 331],
      ['parroquia' => 'Rafael Maria Baralt', 'municipio_id' => 332],
      ['parroquia' => 'Manuel Manrique', 'municipio_id' => 332],
      ['parroquia' => 'Rafael Urdaneta', 'municipio_id' => 332],
      ['parroquia' => 'Bobures', 'municipio_id' => 333],
      ['parroquia' => 'Gibraltar', 'municipio_id' => 333],
      ['parroquia' => 'Heras', 'municipio_id' => 333],
      ['parroquia' => 'Monseñor Arturo Álvarez', 'municipio_id' => 333],
      ['parroquia' => 'Rómulo Gallegos', 'municipio_id' => 333],
      ['parroquia' => 'El Batey', 'municipio_id' => 333],
      ['parroquia' => 'Rafael Urdaneta', 'municipio_id' => 334],
      ['parroquia' => 'La Victoria', 'municipio_id' => 334],
      ['parroquia' => 'Raúl Cuenca', 'municipio_id' => 334],
      ['parroquia' => '23 de enero', 'municipio_id' => 335],
      ['parroquia' => 'Altagracia', 'municipio_id' => 335],
      ['parroquia' => 'Antímano', 'municipio_id' => 335],
      ['parroquia' => 'Caricuao', 'municipio_id' => 335],
      ['parroquia' => 'Catedral', 'municipio_id' => 335],
      ['parroquia' => 'Coche', 'municipio_id' => 335],
      ['parroquia' => 'El Junquito', 'municipio_id' => 335],
      ['parroquia' => 'El Paraíso', 'municipio_id' => 335],
      ['parroquia' => 'El Recreo', 'municipio_id' => 335],
      ['parroquia' => 'El Valle', 'municipio_id' => 335],
      ['parroquia' => 'Candelaria', 'municipio_id' => 335],
      ['parroquia' => 'La Pastora', 'municipio_id' => 335],
      ['parroquia' => 'La Vega', 'municipio_id' => 335],
      ['parroquia' => 'Macarao', 'municipio_id' => 335],
      ['parroquia' => 'San Agustín', 'municipio_id' => 335],
      ['parroquia' => 'San Bernardino', 'municipio_id' => 335],
      ['parroquia' => 'San José', 'municipio_id' => 335],
      ['parroquia' => 'San Juan', 'municipio_id' => 335],
      ['parroquia' => 'San Pedro', 'municipio_id' => 335],
      ['parroquia' => 'Santa Rosalía', 'municipio_id' => 335],
      ['parroquia' => 'Santa Teresa', 'municipio_id' => 335],
      ['parroquia' => 'Sucre (Catia)', 'municipio_id' => 335],
    ];
    DB::table(table: 'parroquias')->insert($parroquias);
  }
}
